// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUM_MAKGA_H_
#define FLATBUFFERS_GENERATED_ENUM_MAKGA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "version_generated.h"

namespace makga {

enum ServerType : int32_t {
  ServerType_Billing = 0,
  ServerType_Login = 1,
  ServerType_World = 2,
  ServerType_Community = 3,
  ServerType_DBAgent = 4,
  ServerType_Game = 5,
  ServerType_Instance = 6,
  ServerType_Web = 7,
  ServerType_Log = 8,
  ServerType_MIN = ServerType_Billing,
  ServerType_MAX = ServerType_Log
};

inline const ServerType (&EnumValuesServerType())[9] {
  static const ServerType values[] = {
    ServerType_Billing,
    ServerType_Login,
    ServerType_World,
    ServerType_Community,
    ServerType_DBAgent,
    ServerType_Game,
    ServerType_Instance,
    ServerType_Web,
    ServerType_Log
  };
  return values;
}

inline const char * const *EnumNamesServerType() {
  static const char * const names[10] = {
    "Billing",
    "Login",
    "World",
    "Community",
    "DBAgent",
    "Game",
    "Instance",
    "Web",
    "Log",
    nullptr
  };
  return names;
}

inline const char *EnumNameServerType(ServerType e) {
  if (::flatbuffers::IsOutRange(e, ServerType_Billing, ServerType_Log)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesServerType()[index];
}

inline bool EnumStringServerType(const char* const str, ServerType e) {
  std::size_t count = static_cast<std::size_t>(ServerType_Log);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesServerType()[i] == str) { e = static_cast<ServerType>(i); return true; }
  }
  return false;
}

enum DatabaseType : int32_t {
  DatabaseType_NONE = 0,
  DatabaseType_MIN = DatabaseType_NONE,
  DatabaseType_MAX = DatabaseType_NONE
};

inline const DatabaseType (&EnumValuesDatabaseType())[1] {
  static const DatabaseType values[] = {
    DatabaseType_NONE
  };
  return values;
}

inline const char * const *EnumNamesDatabaseType() {
  static const char * const names[2] = {
    "NONE",
    nullptr
  };
  return names;
}

inline const char *EnumNameDatabaseType(DatabaseType e) {
  if (::flatbuffers::IsOutRange(e, DatabaseType_NONE, DatabaseType_NONE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDatabaseType()[index];
}

inline bool EnumStringDatabaseType(const char* const str, DatabaseType e) {
  std::size_t count = static_cast<std::size_t>(DatabaseType_NONE);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesDatabaseType()[i] == str) { e = static_cast<DatabaseType>(i); return true; }
  }
  return false;
}

enum RedisType : int32_t {
  RedisType_NONE = 0,
  RedisType_MIN = RedisType_NONE,
  RedisType_MAX = RedisType_NONE
};

inline const RedisType (&EnumValuesRedisType())[1] {
  static const RedisType values[] = {
    RedisType_NONE
  };
  return values;
}

inline const char * const *EnumNamesRedisType() {
  static const char * const names[2] = {
    "NONE",
    nullptr
  };
  return names;
}

inline const char *EnumNameRedisType(RedisType e) {
  if (::flatbuffers::IsOutRange(e, RedisType_NONE, RedisType_NONE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRedisType()[index];
}

inline bool EnumStringRedisType(const char* const str, RedisType e) {
  std::size_t count = static_cast<std::size_t>(RedisType_NONE);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesRedisType()[i] == str) { e = static_cast<RedisType>(i); return true; }
  }
  return false;
}

enum AccountType : int32_t {
  AccountType_NONE = 0,
  AccountType_MIN = AccountType_NONE,
  AccountType_MAX = AccountType_NONE
};

inline const AccountType (&EnumValuesAccountType())[1] {
  static const AccountType values[] = {
    AccountType_NONE
  };
  return values;
}

inline const char * const *EnumNamesAccountType() {
  static const char * const names[2] = {
    "NONE",
    nullptr
  };
  return names;
}

inline const char *EnumNameAccountType(AccountType e) {
  if (::flatbuffers::IsOutRange(e, AccountType_NONE, AccountType_NONE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAccountType()[index];
}

inline bool EnumStringAccountType(const char* const str, AccountType e) {
  std::size_t count = static_cast<std::size_t>(AccountType_NONE);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesAccountType()[i] == str) { e = static_cast<AccountType>(i); return true; }
  }
  return false;
}

enum SessionType : int32_t {
  SessionType_None = 0,
  SessionType_User = 1,
  SessionType_MIN = SessionType_None,
  SessionType_MAX = SessionType_User
};

inline const SessionType (&EnumValuesSessionType())[2] {
  static const SessionType values[] = {
    SessionType_None,
    SessionType_User
  };
  return values;
}

inline const char * const *EnumNamesSessionType() {
  static const char * const names[3] = {
    "None",
    "User",
    nullptr
  };
  return names;
}

inline const char *EnumNameSessionType(SessionType e) {
  if (::flatbuffers::IsOutRange(e, SessionType_None, SessionType_User)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSessionType()[index];
}

inline bool EnumStringSessionType(const char* const str, SessionType e) {
  std::size_t count = static_cast<std::size_t>(SessionType_User);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesSessionType()[i] == str) { e = static_cast<SessionType>(i); return true; }
  }
  return false;
}

enum MessageType : int32_t {
  MessageType_GridAddActor = 0,
  MessageType_GridRemoveActor = 1,
  MessageType_GridBroadcastMove = 2,
  MessageType_TerrainRegisterActor = 3,
  MessageType_TerrainUnregisterActor = 4,
  MessageType_ActorRequestMove = 5,
  MessageType_ActorSetTarget = 6,
  MessageType_ActorSetLeader = 7,
  MessageType_ActorSetOwner = 8,
  MessageType_ActorDelete = 9,
  MessageType_ActorAttack = 10,
  MessageType_ActorAttackResponse = 11,
  MessageType_ActorMoveResponse = 12,
  MessageType_ActorSee = 13,
  MessageType_CharacterSpawn = 14,
  MessageType_CharacterDespawn = 15,
  MessageType_MonsterSpawn = 16,
  MessageType_MonsterDespawn = 17,
  MessageType_MonsterAggravate = 18,
  MessageType_CharacterReceiveLoot = 19,
  MessageType_MIN = MessageType_GridAddActor,
  MessageType_MAX = MessageType_CharacterReceiveLoot
};

inline const MessageType (&EnumValuesMessageType())[20] {
  static const MessageType values[] = {
    MessageType_GridAddActor,
    MessageType_GridRemoveActor,
    MessageType_GridBroadcastMove,
    MessageType_TerrainRegisterActor,
    MessageType_TerrainUnregisterActor,
    MessageType_ActorRequestMove,
    MessageType_ActorSetTarget,
    MessageType_ActorSetLeader,
    MessageType_ActorSetOwner,
    MessageType_ActorDelete,
    MessageType_ActorAttack,
    MessageType_ActorAttackResponse,
    MessageType_ActorMoveResponse,
    MessageType_ActorSee,
    MessageType_CharacterSpawn,
    MessageType_CharacterDespawn,
    MessageType_MonsterSpawn,
    MessageType_MonsterDespawn,
    MessageType_MonsterAggravate,
    MessageType_CharacterReceiveLoot
  };
  return values;
}

inline const char * const *EnumNamesMessageType() {
  static const char * const names[21] = {
    "GridAddActor",
    "GridRemoveActor",
    "GridBroadcastMove",
    "TerrainRegisterActor",
    "TerrainUnregisterActor",
    "ActorRequestMove",
    "ActorSetTarget",
    "ActorSetLeader",
    "ActorSetOwner",
    "ActorDelete",
    "ActorAttack",
    "ActorAttackResponse",
    "ActorMoveResponse",
    "ActorSee",
    "CharacterSpawn",
    "CharacterDespawn",
    "MonsterSpawn",
    "MonsterDespawn",
    "MonsterAggravate",
    "CharacterReceiveLoot",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageType(MessageType e) {
  if (::flatbuffers::IsOutRange(e, MessageType_GridAddActor, MessageType_CharacterReceiveLoot)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageType()[index];
}

inline bool EnumStringMessageType(const char* const str, MessageType e) {
  std::size_t count = static_cast<std::size_t>(MessageType_CharacterReceiveLoot);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesMessageType()[i] == str) { e = static_cast<MessageType>(i); return true; }
  }
  return false;
}

enum TickGroup : int32_t {
  TickGroup_PrePhysics = 0,
  TickGroup_Physics = 1,
  TickGroup_PostPhysics = 2,
  TickGroup_PostUpdate = 3,
  TickGroup_Max = 4,
  TickGroup_MIN = TickGroup_PrePhysics,
  TickGroup_MAX = TickGroup_Max
};

inline const TickGroup (&EnumValuesTickGroup())[5] {
  static const TickGroup values[] = {
    TickGroup_PrePhysics,
    TickGroup_Physics,
    TickGroup_PostPhysics,
    TickGroup_PostUpdate,
    TickGroup_Max
  };
  return values;
}

inline const char * const *EnumNamesTickGroup() {
  static const char * const names[6] = {
    "PrePhysics",
    "Physics",
    "PostPhysics",
    "PostUpdate",
    "Max",
    nullptr
  };
  return names;
}

inline const char *EnumNameTickGroup(TickGroup e) {
  if (::flatbuffers::IsOutRange(e, TickGroup_PrePhysics, TickGroup_Max)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTickGroup()[index];
}

inline bool EnumStringTickGroup(const char* const str, TickGroup e) {
  std::size_t count = static_cast<std::size_t>(TickGroup_Max);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesTickGroup()[i] == str) { e = static_cast<TickGroup>(i); return true; }
  }
  return false;
}

enum AIType : int32_t {
  AIType_Aggressive = 0,
  AIType_NonAggressive = 1,
  AIType_Coward = 2,
  AIType_FieldBoss = 3,
  AIType_InstanceBoss = 4,
  AIType_Character = 5,
  AIType_Sandbag = 6,
  AIType_MIN = AIType_Aggressive,
  AIType_MAX = AIType_Sandbag
};

inline const AIType (&EnumValuesAIType())[7] {
  static const AIType values[] = {
    AIType_Aggressive,
    AIType_NonAggressive,
    AIType_Coward,
    AIType_FieldBoss,
    AIType_InstanceBoss,
    AIType_Character,
    AIType_Sandbag
  };
  return values;
}

inline const char * const *EnumNamesAIType() {
  static const char * const names[8] = {
    "Aggressive",
    "NonAggressive",
    "Coward",
    "FieldBoss",
    "InstanceBoss",
    "Character",
    "Sandbag",
    nullptr
  };
  return names;
}

inline const char *EnumNameAIType(AIType e) {
  if (::flatbuffers::IsOutRange(e, AIType_Aggressive, AIType_Sandbag)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAIType()[index];
}

inline bool EnumStringAIType(const char* const str, AIType e) {
  std::size_t count = static_cast<std::size_t>(AIType_Sandbag);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesAIType()[i] == str) { e = static_cast<AIType>(i); return true; }
  }
  return false;
}

enum ActorType : int32_t {
  ActorType_None = 0,
  ActorType_Character = 1,
  ActorType_Monster = 2,
  ActorType_Gadget = 3,
  ActorType_Object = 4,
  ActorType_MIN = ActorType_None,
  ActorType_MAX = ActorType_Object
};

inline const ActorType (&EnumValuesActorType())[5] {
  static const ActorType values[] = {
    ActorType_None,
    ActorType_Character,
    ActorType_Monster,
    ActorType_Gadget,
    ActorType_Object
  };
  return values;
}

inline const char * const *EnumNamesActorType() {
  static const char * const names[6] = {
    "None",
    "Character",
    "Monster",
    "Gadget",
    "Object",
    nullptr
  };
  return names;
}

inline const char *EnumNameActorType(ActorType e) {
  if (::flatbuffers::IsOutRange(e, ActorType_None, ActorType_Object)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesActorType()[index];
}

inline bool EnumStringActorType(const char* const str, ActorType e) {
  std::size_t count = static_cast<std::size_t>(ActorType_Object);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesActorType()[i] == str) { e = static_cast<ActorType>(i); return true; }
  }
  return false;
}

enum CityType : int32_t {
  CityType_NONE = 0,
  CityType_MIN = CityType_NONE,
  CityType_MAX = CityType_NONE
};

inline const CityType (&EnumValuesCityType())[1] {
  static const CityType values[] = {
    CityType_NONE
  };
  return values;
}

inline const char * const *EnumNamesCityType() {
  static const char * const names[2] = {
    "NONE",
    nullptr
  };
  return names;
}

inline const char *EnumNameCityType(CityType e) {
  if (::flatbuffers::IsOutRange(e, CityType_NONE, CityType_NONE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCityType()[index];
}

inline bool EnumStringCityType(const char* const str, CityType e) {
  std::size_t count = static_cast<std::size_t>(CityType_NONE);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesCityType()[i] == str) { e = static_cast<CityType>(i); return true; }
  }
  return false;
}

enum PkType : int32_t {
  PkType_Safe = 0,
  PkType_Lawful = 1,
  PkType_Conflict = 2,
  PkType_Hostile = 3,
  PkType_Arena = 4,
  PkType_MIN = PkType_Safe,
  PkType_MAX = PkType_Arena
};

inline const PkType (&EnumValuesPkType())[5] {
  static const PkType values[] = {
    PkType_Safe,
    PkType_Lawful,
    PkType_Conflict,
    PkType_Hostile,
    PkType_Arena
  };
  return values;
}

inline const char * const *EnumNamesPkType() {
  static const char * const names[6] = {
    "Safe",
    "Lawful",
    "Conflict",
    "Hostile",
    "Arena",
    nullptr
  };
  return names;
}

inline const char *EnumNamePkType(PkType e) {
  if (::flatbuffers::IsOutRange(e, PkType_Safe, PkType_Arena)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPkType()[index];
}

inline bool EnumStringPkType(const char* const str, PkType e) {
  std::size_t count = static_cast<std::size_t>(PkType_Arena);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesPkType()[i] == str) { e = static_cast<PkType>(i); return true; }
  }
  return false;
}

enum AreaType : int32_t {
  AreaType_City = 0,
  AreaType_Village = 1,
  AreaType_Field = 2,
  AreaType_Instance = 3,
  AreaType_MIN = AreaType_City,
  AreaType_MAX = AreaType_Instance
};

inline const AreaType (&EnumValuesAreaType())[4] {
  static const AreaType values[] = {
    AreaType_City,
    AreaType_Village,
    AreaType_Field,
    AreaType_Instance
  };
  return values;
}

inline const char * const *EnumNamesAreaType() {
  static const char * const names[5] = {
    "City",
    "Village",
    "Field",
    "Instance",
    nullptr
  };
  return names;
}

inline const char *EnumNameAreaType(AreaType e) {
  if (::flatbuffers::IsOutRange(e, AreaType_City, AreaType_Instance)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAreaType()[index];
}

inline bool EnumStringAreaType(const char* const str, AreaType e) {
  std::size_t count = static_cast<std::size_t>(AreaType_Instance);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesAreaType()[i] == str) { e = static_cast<AreaType>(i); return true; }
  }
  return false;
}

enum AttributeType : int32_t {
  AttributeType_None = 0,
  AttributeType_Fire = 1,
  AttributeType_Water = 2,
  AttributeType_Wind = 3,
  AttributeType_Earth = 4,
  AttributeType_Holy = 5,
  AttributeType_Dark = 6,
  AttributeType_MIN = AttributeType_None,
  AttributeType_MAX = AttributeType_Dark
};

inline const AttributeType (&EnumValuesAttributeType())[7] {
  static const AttributeType values[] = {
    AttributeType_None,
    AttributeType_Fire,
    AttributeType_Water,
    AttributeType_Wind,
    AttributeType_Earth,
    AttributeType_Holy,
    AttributeType_Dark
  };
  return values;
}

inline const char * const *EnumNamesAttributeType() {
  static const char * const names[8] = {
    "None",
    "Fire",
    "Water",
    "Wind",
    "Earth",
    "Holy",
    "Dark",
    nullptr
  };
  return names;
}

inline const char *EnumNameAttributeType(AttributeType e) {
  if (::flatbuffers::IsOutRange(e, AttributeType_None, AttributeType_Dark)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAttributeType()[index];
}

inline bool EnumStringAttributeType(const char* const str, AttributeType e) {
  std::size_t count = static_cast<std::size_t>(AttributeType_Dark);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesAttributeType()[i] == str) { e = static_cast<AttributeType>(i); return true; }
  }
  return false;
}

enum RaceType : int32_t {
  RaceType_Human = 0,
  RaceType_Elf = 1,
  RaceType_Dwarf = 2,
  RaceType_Orc = 3,
  RaceType_Undead = 4,
  RaceType_Dragon = 5,
  RaceType_MIN = RaceType_Human,
  RaceType_MAX = RaceType_Dragon
};

inline const RaceType (&EnumValuesRaceType())[6] {
  static const RaceType values[] = {
    RaceType_Human,
    RaceType_Elf,
    RaceType_Dwarf,
    RaceType_Orc,
    RaceType_Undead,
    RaceType_Dragon
  };
  return values;
}

inline const char * const *EnumNamesRaceType() {
  static const char * const names[7] = {
    "Human",
    "Elf",
    "Dwarf",
    "Orc",
    "Undead",
    "Dragon",
    nullptr
  };
  return names;
}

inline const char *EnumNameRaceType(RaceType e) {
  if (::flatbuffers::IsOutRange(e, RaceType_Human, RaceType_Dragon)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRaceType()[index];
}

inline bool EnumStringRaceType(const char* const str, RaceType e) {
  std::size_t count = static_cast<std::size_t>(RaceType_Dragon);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesRaceType()[i] == str) { e = static_cast<RaceType>(i); return true; }
  }
  return false;
}

enum CurrencyType : int32_t {
  CurrencyType_Gold = 0,
  CurrencyType_Ruby = 1,
  CurrencyType_Mileage = 2,
  CurrencyType_Honor = 3,
  CurrencyType_GuildPoint = 4,
  CurrencyType_MIN = CurrencyType_Gold,
  CurrencyType_MAX = CurrencyType_GuildPoint
};

inline const CurrencyType (&EnumValuesCurrencyType())[5] {
  static const CurrencyType values[] = {
    CurrencyType_Gold,
    CurrencyType_Ruby,
    CurrencyType_Mileage,
    CurrencyType_Honor,
    CurrencyType_GuildPoint
  };
  return values;
}

inline const char * const *EnumNamesCurrencyType() {
  static const char * const names[6] = {
    "Gold",
    "Ruby",
    "Mileage",
    "Honor",
    "GuildPoint",
    nullptr
  };
  return names;
}

inline const char *EnumNameCurrencyType(CurrencyType e) {
  if (::flatbuffers::IsOutRange(e, CurrencyType_Gold, CurrencyType_GuildPoint)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCurrencyType()[index];
}

inline bool EnumStringCurrencyType(const char* const str, CurrencyType e) {
  std::size_t count = static_cast<std::size_t>(CurrencyType_GuildPoint);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesCurrencyType()[i] == str) { e = static_cast<CurrencyType>(i); return true; }
  }
  return false;
}

enum GradeType : int32_t {
  GradeType_Normal = 0,
  GradeType_Magic = 1,
  GradeType_Rare = 2,
  GradeType_Unique = 3,
  GradeType_Epic = 4,
  GradeType_Legendary = 5,
  GradeType_Mythic = 6,
  GradeType_MIN = GradeType_Normal,
  GradeType_MAX = GradeType_Mythic
};

inline const GradeType (&EnumValuesGradeType())[7] {
  static const GradeType values[] = {
    GradeType_Normal,
    GradeType_Magic,
    GradeType_Rare,
    GradeType_Unique,
    GradeType_Epic,
    GradeType_Legendary,
    GradeType_Mythic
  };
  return values;
}

inline const char * const *EnumNamesGradeType() {
  static const char * const names[8] = {
    "Normal",
    "Magic",
    "Rare",
    "Unique",
    "Epic",
    "Legendary",
    "Mythic",
    nullptr
  };
  return names;
}

inline const char *EnumNameGradeType(GradeType e) {
  if (::flatbuffers::IsOutRange(e, GradeType_Normal, GradeType_Mythic)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGradeType()[index];
}

inline bool EnumStringGradeType(const char* const str, GradeType e) {
  std::size_t count = static_cast<std::size_t>(GradeType_Mythic);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesGradeType()[i] == str) { e = static_cast<GradeType>(i); return true; }
  }
  return false;
}

enum StatType : int32_t {
  StatType_Strength = 0,
  StatType_Agility = 1,
  StatType_Intelligence = 2,
  StatType_Stamina = 3,
  StatType_Dexterity = 4,
  StatType_Wisdom = 5,
  StatType_Luck = 6,
  StatType_Constitution = 7,
  StatType_Spirit = 8,
  StatType_Charisma = 9,
  StatType_Hp = 10,
  StatType_Mp = 11,
  StatType_HpRegen = 12,
  StatType_MpRegen = 13,
  StatType_AttackSpeed = 14,
  StatType_CastSpeed = 15,
  StatType_MoveSpeed = 16,
  StatType_Accuracy = 17,
  StatType_Penetration = 18,
  StatType_MagicPenetration = 19,
  StatType_SkillDamage = 20,
  StatType_BonusDamage = 21,
  StatType_DamageReduction = 22,
  StatType_BossDamage = 23,
  StatType_PhysicalAtk = 24,
  StatType_PhysicalDef = 25,
  StatType_MagicalAtk = 26,
  StatType_MagicalDef = 27,
  StatType_FireDamage = 28,
  StatType_FireReduction = 29,
  StatType_WaterDamage = 30,
  StatType_WaterReduction = 31,
  StatType_WindDamage = 32,
  StatType_WindReduction = 33,
  StatType_EarthDamage = 34,
  StatType_EarthReduction = 35,
  StatType_HolyDamage = 36,
  StatType_HolyReduction = 37,
  StatType_DarkDamage = 38,
  StatType_DarkReduction = 39,
  StatType_CriRate = 40,
  StatType_CriResist = 41,
  StatType_CriDamage = 42,
  StatType_CriReduction = 43,
  StatType_BlockRate = 44,
  StatType_BlockResist = 45,
  StatType_MIN = StatType_Strength,
  StatType_MAX = StatType_BlockResist
};

inline const StatType (&EnumValuesStatType())[46] {
  static const StatType values[] = {
    StatType_Strength,
    StatType_Agility,
    StatType_Intelligence,
    StatType_Stamina,
    StatType_Dexterity,
    StatType_Wisdom,
    StatType_Luck,
    StatType_Constitution,
    StatType_Spirit,
    StatType_Charisma,
    StatType_Hp,
    StatType_Mp,
    StatType_HpRegen,
    StatType_MpRegen,
    StatType_AttackSpeed,
    StatType_CastSpeed,
    StatType_MoveSpeed,
    StatType_Accuracy,
    StatType_Penetration,
    StatType_MagicPenetration,
    StatType_SkillDamage,
    StatType_BonusDamage,
    StatType_DamageReduction,
    StatType_BossDamage,
    StatType_PhysicalAtk,
    StatType_PhysicalDef,
    StatType_MagicalAtk,
    StatType_MagicalDef,
    StatType_FireDamage,
    StatType_FireReduction,
    StatType_WaterDamage,
    StatType_WaterReduction,
    StatType_WindDamage,
    StatType_WindReduction,
    StatType_EarthDamage,
    StatType_EarthReduction,
    StatType_HolyDamage,
    StatType_HolyReduction,
    StatType_DarkDamage,
    StatType_DarkReduction,
    StatType_CriRate,
    StatType_CriResist,
    StatType_CriDamage,
    StatType_CriReduction,
    StatType_BlockRate,
    StatType_BlockResist
  };
  return values;
}

inline const char * const *EnumNamesStatType() {
  static const char * const names[47] = {
    "Strength",
    "Agility",
    "Intelligence",
    "Stamina",
    "Dexterity",
    "Wisdom",
    "Luck",
    "Constitution",
    "Spirit",
    "Charisma",
    "Hp",
    "Mp",
    "HpRegen",
    "MpRegen",
    "AttackSpeed",
    "CastSpeed",
    "MoveSpeed",
    "Accuracy",
    "Penetration",
    "MagicPenetration",
    "SkillDamage",
    "BonusDamage",
    "DamageReduction",
    "BossDamage",
    "PhysicalAtk",
    "PhysicalDef",
    "MagicalAtk",
    "MagicalDef",
    "FireDamage",
    "FireReduction",
    "WaterDamage",
    "WaterReduction",
    "WindDamage",
    "WindReduction",
    "EarthDamage",
    "EarthReduction",
    "HolyDamage",
    "HolyReduction",
    "DarkDamage",
    "DarkReduction",
    "CriRate",
    "CriResist",
    "CriDamage",
    "CriReduction",
    "BlockRate",
    "BlockResist",
    nullptr
  };
  return names;
}

inline const char *EnumNameStatType(StatType e) {
  if (::flatbuffers::IsOutRange(e, StatType_Strength, StatType_BlockResist)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStatType()[index];
}

inline bool EnumStringStatType(const char* const str, StatType e) {
  std::size_t count = static_cast<std::size_t>(StatType_BlockResist);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesStatType()[i] == str) { e = static_cast<StatType>(i); return true; }
  }
  return false;
}

enum AbilityType : int32_t {
  AbilityType_Stun = 0,
  AbilityType_Knockback = 1,
  AbilityType_Slow = 2,
  AbilityType_Provoke = 3,
  AbilityType_Silence = 4,
  AbilityType_Blessing = 5,
  AbilityType_DoubleHitChance = 6,
  AbilityType_IgnoreShield = 7,
  AbilityType_LifeSteal = 8,
  AbilityType_Shield = 9,
  AbilityType_HealingUp = 10,
  AbilityType_CoolTimeDown = 11,
  AbilityType_Burn = 12,
  AbilityType_Curse = 13,
  AbilityType_Immortal = 14,
  AbilityType_MIN = AbilityType_Stun,
  AbilityType_MAX = AbilityType_Immortal
};

inline const AbilityType (&EnumValuesAbilityType())[15] {
  static const AbilityType values[] = {
    AbilityType_Stun,
    AbilityType_Knockback,
    AbilityType_Slow,
    AbilityType_Provoke,
    AbilityType_Silence,
    AbilityType_Blessing,
    AbilityType_DoubleHitChance,
    AbilityType_IgnoreShield,
    AbilityType_LifeSteal,
    AbilityType_Shield,
    AbilityType_HealingUp,
    AbilityType_CoolTimeDown,
    AbilityType_Burn,
    AbilityType_Curse,
    AbilityType_Immortal
  };
  return values;
}

inline const char * const *EnumNamesAbilityType() {
  static const char * const names[16] = {
    "Stun",
    "Knockback",
    "Slow",
    "Provoke",
    "Silence",
    "Blessing",
    "DoubleHitChance",
    "IgnoreShield",
    "LifeSteal",
    "Shield",
    "HealingUp",
    "CoolTimeDown",
    "Burn",
    "Curse",
    "Immortal",
    nullptr
  };
  return names;
}

inline const char *EnumNameAbilityType(AbilityType e) {
  if (::flatbuffers::IsOutRange(e, AbilityType_Stun, AbilityType_Immortal)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAbilityType()[index];
}

inline bool EnumStringAbilityType(const char* const str, AbilityType e) {
  std::size_t count = static_cast<std::size_t>(AbilityType_Immortal);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesAbilityType()[i] == str) { e = static_cast<AbilityType>(i); return true; }
  }
  return false;
}

enum TargetingType : int32_t {
  TargetingType_Self = 0,
  TargetingType_Unit = 1,
  TargetingType_Ground = 2,
  TargetingType_MIN = TargetingType_Self,
  TargetingType_MAX = TargetingType_Ground
};

inline const TargetingType (&EnumValuesTargetingType())[3] {
  static const TargetingType values[] = {
    TargetingType_Self,
    TargetingType_Unit,
    TargetingType_Ground
  };
  return values;
}

inline const char * const *EnumNamesTargetingType() {
  static const char * const names[4] = {
    "Self",
    "Unit",
    "Ground",
    nullptr
  };
  return names;
}

inline const char *EnumNameTargetingType(TargetingType e) {
  if (::flatbuffers::IsOutRange(e, TargetingType_Self, TargetingType_Ground)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTargetingType()[index];
}

inline bool EnumStringTargetingType(const char* const str, TargetingType e) {
  std::size_t count = static_cast<std::size_t>(TargetingType_Ground);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesTargetingType()[i] == str) { e = static_cast<TargetingType>(i); return true; }
  }
  return false;
}

enum CostType : int32_t {
  CostType_Gold = 0,
  CostType_Hp = 1,
  CostType_Mp = 2,
  CostType_MIN = CostType_Gold,
  CostType_MAX = CostType_Mp
};

inline const CostType (&EnumValuesCostType())[3] {
  static const CostType values[] = {
    CostType_Gold,
    CostType_Hp,
    CostType_Mp
  };
  return values;
}

inline const char * const *EnumNamesCostType() {
  static const char * const names[4] = {
    "Gold",
    "Hp",
    "Mp",
    nullptr
  };
  return names;
}

inline const char *EnumNameCostType(CostType e) {
  if (::flatbuffers::IsOutRange(e, CostType_Gold, CostType_Mp)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCostType()[index];
}

inline bool EnumStringCostType(const char* const str, CostType e) {
  std::size_t count = static_cast<std::size_t>(CostType_Mp);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesCostType()[i] == str) { e = static_cast<CostType>(i); return true; }
  }
  return false;
}

enum ItemReason : int32_t {
  ItemReason_AddDrop = 0,
  ItemReason_SubUse = 1,
  ItemReason_MIN = ItemReason_AddDrop,
  ItemReason_MAX = ItemReason_SubUse
};

inline const ItemReason (&EnumValuesItemReason())[2] {
  static const ItemReason values[] = {
    ItemReason_AddDrop,
    ItemReason_SubUse
  };
  return values;
}

inline const char * const *EnumNamesItemReason() {
  static const char * const names[3] = {
    "AddDrop",
    "SubUse",
    nullptr
  };
  return names;
}

inline const char *EnumNameItemReason(ItemReason e) {
  if (::flatbuffers::IsOutRange(e, ItemReason_AddDrop, ItemReason_SubUse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesItemReason()[index];
}

inline bool EnumStringItemReason(const char* const str, ItemReason e) {
  std::size_t count = static_cast<std::size_t>(ItemReason_SubUse);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesItemReason()[i] == str) { e = static_cast<ItemReason>(i); return true; }
  }
  return false;
}

enum DamageType : int32_t {
  DamageType_Physical = 0,
  DamageType_Magical = 1,
  DamageType_True = 2,
  DamageType_Holy = 3,
  DamageType_Dark = 4,
  DamageType_Fire = 5,
  DamageType_Ice = 6,
  DamageType_Lightning = 7,
  DamageType_Earth = 8,
  DamageType_Bleed = 9,
  DamageType_Poison = 10,
  DamageType_MIN = DamageType_Physical,
  DamageType_MAX = DamageType_Poison
};

inline const DamageType (&EnumValuesDamageType())[11] {
  static const DamageType values[] = {
    DamageType_Physical,
    DamageType_Magical,
    DamageType_True,
    DamageType_Holy,
    DamageType_Dark,
    DamageType_Fire,
    DamageType_Ice,
    DamageType_Lightning,
    DamageType_Earth,
    DamageType_Bleed,
    DamageType_Poison
  };
  return values;
}

inline const char * const *EnumNamesDamageType() {
  static const char * const names[12] = {
    "Physical",
    "Magical",
    "True",
    "Holy",
    "Dark",
    "Fire",
    "Ice",
    "Lightning",
    "Earth",
    "Bleed",
    "Poison",
    nullptr
  };
  return names;
}

inline const char *EnumNameDamageType(DamageType e) {
  if (::flatbuffers::IsOutRange(e, DamageType_Physical, DamageType_Poison)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDamageType()[index];
}

inline bool EnumStringDamageType(const char* const str, DamageType e) {
  std::size_t count = static_cast<std::size_t>(DamageType_Poison);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesDamageType()[i] == str) { e = static_cast<DamageType>(i); return true; }
  }
  return false;
}

enum MonsterType : int32_t {
  MonsterType_Beast = 0,
  MonsterType_Undead = 1,
  MonsterType_Demon = 2,
  MonsterType_Dragon = 3,
  MonsterType_Elemental = 4,
  MonsterType_HolyBeing = 5,
  MonsterType_DarkBeing = 6,
  MonsterType_Human = 7,
  MonsterType_Plant = 8,
  MonsterType_Construct = 9,
  MonsterType_MIN = MonsterType_Beast,
  MonsterType_MAX = MonsterType_Construct
};

inline const MonsterType (&EnumValuesMonsterType())[10] {
  static const MonsterType values[] = {
    MonsterType_Beast,
    MonsterType_Undead,
    MonsterType_Demon,
    MonsterType_Dragon,
    MonsterType_Elemental,
    MonsterType_HolyBeing,
    MonsterType_DarkBeing,
    MonsterType_Human,
    MonsterType_Plant,
    MonsterType_Construct
  };
  return values;
}

inline const char * const *EnumNamesMonsterType() {
  static const char * const names[11] = {
    "Beast",
    "Undead",
    "Demon",
    "Dragon",
    "Elemental",
    "HolyBeing",
    "DarkBeing",
    "Human",
    "Plant",
    "Construct",
    nullptr
  };
  return names;
}

inline const char *EnumNameMonsterType(MonsterType e) {
  if (::flatbuffers::IsOutRange(e, MonsterType_Beast, MonsterType_Construct)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMonsterType()[index];
}

inline bool EnumStringMonsterType(const char* const str, MonsterType e) {
  std::size_t count = static_cast<std::size_t>(MonsterType_Construct);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesMonsterType()[i] == str) { e = static_cast<MonsterType>(i); return true; }
  }
  return false;
}

enum StatusEffectType : int32_t {
  StatusEffectType_Bleed = 0,
  StatusEffectType_Fracture = 1,
  StatusEffectType_Root = 2,
  StatusEffectType_Poison = 3,
  StatusEffectType_Freeze = 4,
  StatusEffectType_Electrify = 5,
  StatusEffectType_Ignite = 6,
  StatusEffectType_Petrify = 7,
  StatusEffectType_Blind = 8,
  StatusEffectType_Reveal = 9,
  StatusEffectType_HolyMark = 10,
  StatusEffectType_Curse = 11,
  StatusEffectType_Fear = 12,
  StatusEffectType_Decay = 13,
  StatusEffectType_DarkMark = 14,
  StatusEffectType_Stun = 15,
  StatusEffectType_Sleep = 16,
  StatusEffectType_Silence = 17,
  StatusEffectType_Slow = 18,
  StatusEffectType_Knockback = 19,
  StatusEffectType_MIN = StatusEffectType_Bleed,
  StatusEffectType_MAX = StatusEffectType_Knockback
};

inline const StatusEffectType (&EnumValuesStatusEffectType())[20] {
  static const StatusEffectType values[] = {
    StatusEffectType_Bleed,
    StatusEffectType_Fracture,
    StatusEffectType_Root,
    StatusEffectType_Poison,
    StatusEffectType_Freeze,
    StatusEffectType_Electrify,
    StatusEffectType_Ignite,
    StatusEffectType_Petrify,
    StatusEffectType_Blind,
    StatusEffectType_Reveal,
    StatusEffectType_HolyMark,
    StatusEffectType_Curse,
    StatusEffectType_Fear,
    StatusEffectType_Decay,
    StatusEffectType_DarkMark,
    StatusEffectType_Stun,
    StatusEffectType_Sleep,
    StatusEffectType_Silence,
    StatusEffectType_Slow,
    StatusEffectType_Knockback
  };
  return values;
}

inline const char * const *EnumNamesStatusEffectType() {
  static const char * const names[21] = {
    "Bleed",
    "Fracture",
    "Root",
    "Poison",
    "Freeze",
    "Electrify",
    "Ignite",
    "Petrify",
    "Blind",
    "Reveal",
    "HolyMark",
    "Curse",
    "Fear",
    "Decay",
    "DarkMark",
    "Stun",
    "Sleep",
    "Silence",
    "Slow",
    "Knockback",
    nullptr
  };
  return names;
}

inline const char *EnumNameStatusEffectType(StatusEffectType e) {
  if (::flatbuffers::IsOutRange(e, StatusEffectType_Bleed, StatusEffectType_Knockback)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStatusEffectType()[index];
}

inline bool EnumStringStatusEffectType(const char* const str, StatusEffectType e) {
  std::size_t count = static_cast<std::size_t>(StatusEffectType_Knockback);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesStatusEffectType()[i] == str) { e = static_cast<StatusEffectType>(i); return true; }
  }
  return false;
}

enum DungeonType : int32_t {
  DungeonType_Normal = 0,
  DungeonType_Solo = 1,
  DungeonType_Elite = 2,
  DungeonType_Hard = 3,
  DungeonType_Challenge = 4,
  DungeonType_Raid = 5,
  DungeonType_Special = 6,
  DungeonType_MIN = DungeonType_Normal,
  DungeonType_MAX = DungeonType_Special
};

inline const DungeonType (&EnumValuesDungeonType())[7] {
  static const DungeonType values[] = {
    DungeonType_Normal,
    DungeonType_Solo,
    DungeonType_Elite,
    DungeonType_Hard,
    DungeonType_Challenge,
    DungeonType_Raid,
    DungeonType_Special
  };
  return values;
}

inline const char * const *EnumNamesDungeonType() {
  static const char * const names[8] = {
    "Normal",
    "Solo",
    "Elite",
    "Hard",
    "Challenge",
    "Raid",
    "Special",
    nullptr
  };
  return names;
}

inline const char *EnumNameDungeonType(DungeonType e) {
  if (::flatbuffers::IsOutRange(e, DungeonType_Normal, DungeonType_Special)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDungeonType()[index];
}

inline bool EnumStringDungeonType(const char* const str, DungeonType e) {
  std::size_t count = static_cast<std::size_t>(DungeonType_Special);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesDungeonType()[i] == str) { e = static_cast<DungeonType>(i); return true; }
  }
  return false;
}

enum QuestType : int32_t {
  QuestType_Main = 0,
  QuestType_Sub = 1,
  QuestType_Daily = 2,
  QuestType_Weekly = 3,
  QuestType_Guild = 4,
  QuestType_Bounty = 5,
  QuestType_ClassQuest = 6,
  QuestType_Repeatable = 7,
  QuestType_MIN = QuestType_Main,
  QuestType_MAX = QuestType_Repeatable
};

inline const QuestType (&EnumValuesQuestType())[8] {
  static const QuestType values[] = {
    QuestType_Main,
    QuestType_Sub,
    QuestType_Daily,
    QuestType_Weekly,
    QuestType_Guild,
    QuestType_Bounty,
    QuestType_ClassQuest,
    QuestType_Repeatable
  };
  return values;
}

inline const char * const *EnumNamesQuestType() {
  static const char * const names[9] = {
    "Main",
    "Sub",
    "Daily",
    "Weekly",
    "Guild",
    "Bounty",
    "ClassQuest",
    "Repeatable",
    nullptr
  };
  return names;
}

inline const char *EnumNameQuestType(QuestType e) {
  if (::flatbuffers::IsOutRange(e, QuestType_Main, QuestType_Repeatable)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesQuestType()[index];
}

inline bool EnumStringQuestType(const char* const str, QuestType e) {
  std::size_t count = static_cast<std::size_t>(QuestType_Repeatable);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesQuestType()[i] == str) { e = static_cast<QuestType>(i); return true; }
  }
  return false;
}

enum NPCType : int32_t {
  NPCType_Merchant = 0,
  NPCType_QuestGiver = 1,
  NPCType_Guard = 2,
  NPCType_Blacksmith = 3,
  NPCType_Enchanter = 4,
  NPCType_Alchemist = 5,
  NPCType_Trainer = 6,
  NPCType_GuildMaster = 7,
  NPCType_AuctionClerk = 8,
  NPCType_Banker = 9,
  NPCType_Teleporter = 10,
  NPCType_MIN = NPCType_Merchant,
  NPCType_MAX = NPCType_Teleporter
};

inline const NPCType (&EnumValuesNPCType())[11] {
  static const NPCType values[] = {
    NPCType_Merchant,
    NPCType_QuestGiver,
    NPCType_Guard,
    NPCType_Blacksmith,
    NPCType_Enchanter,
    NPCType_Alchemist,
    NPCType_Trainer,
    NPCType_GuildMaster,
    NPCType_AuctionClerk,
    NPCType_Banker,
    NPCType_Teleporter
  };
  return values;
}

inline const char * const *EnumNamesNPCType() {
  static const char * const names[12] = {
    "Merchant",
    "QuestGiver",
    "Guard",
    "Blacksmith",
    "Enchanter",
    "Alchemist",
    "Trainer",
    "GuildMaster",
    "AuctionClerk",
    "Banker",
    "Teleporter",
    nullptr
  };
  return names;
}

inline const char *EnumNameNPCType(NPCType e) {
  if (::flatbuffers::IsOutRange(e, NPCType_Merchant, NPCType_Teleporter)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNPCType()[index];
}

inline bool EnumStringNPCType(const char* const str, NPCType e) {
  std::size_t count = static_cast<std::size_t>(NPCType_Teleporter);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesNPCType()[i] == str) { e = static_cast<NPCType>(i); return true; }
  }
  return false;
}

enum CraftType : int32_t {
  CraftType_Blacksmithing = 0,
  CraftType_Tailoring = 1,
  CraftType_Leatherwork = 2,
  CraftType_Alchemy = 3,
  CraftType_Cooking = 4,
  CraftType_Enchanting = 5,
  CraftType_Jeweling = 6,
  CraftType_Inscription = 7,
  CraftType_MIN = CraftType_Blacksmithing,
  CraftType_MAX = CraftType_Inscription
};

inline const CraftType (&EnumValuesCraftType())[8] {
  static const CraftType values[] = {
    CraftType_Blacksmithing,
    CraftType_Tailoring,
    CraftType_Leatherwork,
    CraftType_Alchemy,
    CraftType_Cooking,
    CraftType_Enchanting,
    CraftType_Jeweling,
    CraftType_Inscription
  };
  return values;
}

inline const char * const *EnumNamesCraftType() {
  static const char * const names[9] = {
    "Blacksmithing",
    "Tailoring",
    "Leatherwork",
    "Alchemy",
    "Cooking",
    "Enchanting",
    "Jeweling",
    "Inscription",
    nullptr
  };
  return names;
}

inline const char *EnumNameCraftType(CraftType e) {
  if (::flatbuffers::IsOutRange(e, CraftType_Blacksmithing, CraftType_Inscription)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCraftType()[index];
}

inline bool EnumStringCraftType(const char* const str, CraftType e) {
  std::size_t count = static_cast<std::size_t>(CraftType_Inscription);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesCraftType()[i] == str) { e = static_cast<CraftType>(i); return true; }
  }
  return false;
}

enum PartyRole : int32_t {
  PartyRole_Leader = 0,
  PartyRole_Member = 1,
  PartyRole_MIN = PartyRole_Leader,
  PartyRole_MAX = PartyRole_Member
};

inline const PartyRole (&EnumValuesPartyRole())[2] {
  static const PartyRole values[] = {
    PartyRole_Leader,
    PartyRole_Member
  };
  return values;
}

inline const char * const *EnumNamesPartyRole() {
  static const char * const names[3] = {
    "Leader",
    "Member",
    nullptr
  };
  return names;
}

inline const char *EnumNamePartyRole(PartyRole e) {
  if (::flatbuffers::IsOutRange(e, PartyRole_Leader, PartyRole_Member)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPartyRole()[index];
}

inline bool EnumStringPartyRole(const char* const str, PartyRole e) {
  std::size_t count = static_cast<std::size_t>(PartyRole_Member);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesPartyRole()[i] == str) { e = static_cast<PartyRole>(i); return true; }
  }
  return false;
}

enum PartyState : int32_t {
  PartyState_Idle = 0,
  PartyState_InDungeon = 1,
  PartyState_InCombat = 2,
  PartyState_MIN = PartyState_Idle,
  PartyState_MAX = PartyState_InCombat
};

inline const PartyState (&EnumValuesPartyState())[3] {
  static const PartyState values[] = {
    PartyState_Idle,
    PartyState_InDungeon,
    PartyState_InCombat
  };
  return values;
}

inline const char * const *EnumNamesPartyState() {
  static const char * const names[4] = {
    "Idle",
    "InDungeon",
    "InCombat",
    nullptr
  };
  return names;
}

inline const char *EnumNamePartyState(PartyState e) {
  if (::flatbuffers::IsOutRange(e, PartyState_Idle, PartyState_InCombat)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPartyState()[index];
}

inline bool EnumStringPartyState(const char* const str, PartyState e) {
  std::size_t count = static_cast<std::size_t>(PartyState_InCombat);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesPartyState()[i] == str) { e = static_cast<PartyState>(i); return true; }
  }
  return false;
}

enum ExpShareType : int32_t {
  ExpShareType_Equal = 0,
  ExpShareType_Contribution = 1,
  ExpShareType_MIN = ExpShareType_Equal,
  ExpShareType_MAX = ExpShareType_Contribution
};

inline const ExpShareType (&EnumValuesExpShareType())[2] {
  static const ExpShareType values[] = {
    ExpShareType_Equal,
    ExpShareType_Contribution
  };
  return values;
}

inline const char * const *EnumNamesExpShareType() {
  static const char * const names[3] = {
    "Equal",
    "Contribution",
    nullptr
  };
  return names;
}

inline const char *EnumNameExpShareType(ExpShareType e) {
  if (::flatbuffers::IsOutRange(e, ExpShareType_Equal, ExpShareType_Contribution)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesExpShareType()[index];
}

inline bool EnumStringExpShareType(const char* const str, ExpShareType e) {
  std::size_t count = static_cast<std::size_t>(ExpShareType_Contribution);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesExpShareType()[i] == str) { e = static_cast<ExpShareType>(i); return true; }
  }
  return false;
}

enum LootType : int32_t {
  LootType_FreeForAll = 0,
  LootType_RoundRobin = 1,
  LootType_NeedGreed = 2,
  LootType_MIN = LootType_FreeForAll,
  LootType_MAX = LootType_NeedGreed
};

inline const LootType (&EnumValuesLootType())[3] {
  static const LootType values[] = {
    LootType_FreeForAll,
    LootType_RoundRobin,
    LootType_NeedGreed
  };
  return values;
}

inline const char * const *EnumNamesLootType() {
  static const char * const names[4] = {
    "FreeForAll",
    "RoundRobin",
    "NeedGreed",
    nullptr
  };
  return names;
}

inline const char *EnumNameLootType(LootType e) {
  if (::flatbuffers::IsOutRange(e, LootType_FreeForAll, LootType_NeedGreed)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLootType()[index];
}

inline bool EnumStringLootType(const char* const str, LootType e) {
  std::size_t count = static_cast<std::size_t>(LootType_NeedGreed);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesLootType()[i] == str) { e = static_cast<LootType>(i); return true; }
  }
  return false;
}

enum PartyGoalType : int32_t {
  PartyGoalType_Field = 0,
  PartyGoalType_Dungeon = 1,
  PartyGoalType_MIN = PartyGoalType_Field,
  PartyGoalType_MAX = PartyGoalType_Dungeon
};

inline const PartyGoalType (&EnumValuesPartyGoalType())[2] {
  static const PartyGoalType values[] = {
    PartyGoalType_Field,
    PartyGoalType_Dungeon
  };
  return values;
}

inline const char * const *EnumNamesPartyGoalType() {
  static const char * const names[3] = {
    "Field",
    "Dungeon",
    nullptr
  };
  return names;
}

inline const char *EnumNamePartyGoalType(PartyGoalType e) {
  if (::flatbuffers::IsOutRange(e, PartyGoalType_Field, PartyGoalType_Dungeon)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPartyGoalType()[index];
}

inline bool EnumStringPartyGoalType(const char* const str, PartyGoalType e) {
  std::size_t count = static_cast<std::size_t>(PartyGoalType_Dungeon);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesPartyGoalType()[i] == str) { e = static_cast<PartyGoalType>(i); return true; }
  }
  return false;
}

enum EquipSlot : int32_t {
  EquipSlot_None = 0,
  EquipSlot_Helm = 1,
  EquipSlot_Chest = 2,
  EquipSlot_Legs = 3,
  EquipSlot_Gloves = 4,
  EquipSlot_Boots = 5,
  EquipSlot_Cloak = 6,
  EquipSlot_Weapon = 7,
  EquipSlot_OffHand = 8,
  EquipSlot_Ring1 = 9,
  EquipSlot_Ring2 = 10,
  EquipSlot_Necklace = 11,
  EquipSlot_Earring = 12,
  EquipSlot_Belt = 13,
  EquipSlot_Relic = 14,
  EquipSlot_MIN = EquipSlot_None,
  EquipSlot_MAX = EquipSlot_Relic
};

inline const EquipSlot (&EnumValuesEquipSlot())[15] {
  static const EquipSlot values[] = {
    EquipSlot_None,
    EquipSlot_Helm,
    EquipSlot_Chest,
    EquipSlot_Legs,
    EquipSlot_Gloves,
    EquipSlot_Boots,
    EquipSlot_Cloak,
    EquipSlot_Weapon,
    EquipSlot_OffHand,
    EquipSlot_Ring1,
    EquipSlot_Ring2,
    EquipSlot_Necklace,
    EquipSlot_Earring,
    EquipSlot_Belt,
    EquipSlot_Relic
  };
  return values;
}

inline const char * const *EnumNamesEquipSlot() {
  static const char * const names[16] = {
    "None",
    "Helm",
    "Chest",
    "Legs",
    "Gloves",
    "Boots",
    "Cloak",
    "Weapon",
    "OffHand",
    "Ring1",
    "Ring2",
    "Necklace",
    "Earring",
    "Belt",
    "Relic",
    nullptr
  };
  return names;
}

inline const char *EnumNameEquipSlot(EquipSlot e) {
  if (::flatbuffers::IsOutRange(e, EquipSlot_None, EquipSlot_Relic)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEquipSlot()[index];
}

inline bool EnumStringEquipSlot(const char* const str, EquipSlot e) {
  std::size_t count = static_cast<std::size_t>(EquipSlot_Relic);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesEquipSlot()[i] == str) { e = static_cast<EquipSlot>(i); return true; }
  }
  return false;
}

enum ItemType : int32_t {
  ItemType_None = 0,
  ItemType_Weapon = 1,
  ItemType_Armor = 2,
  ItemType_Accessory = 3,
  ItemType_Consumable = 4,
  ItemType_Material = 5,
  ItemType_QuestItem = 6,
  ItemType_Skillbook = 7,
  ItemType_Blueprint = 8,
  ItemType_Relic = 9,
  ItemType_EnchantStone = 10,
  ItemType_Mount = 11,
  ItemType_Pet = 12,
  ItemType_Misc = 13,
  ItemType_MIN = ItemType_None,
  ItemType_MAX = ItemType_Misc
};

inline const ItemType (&EnumValuesItemType())[14] {
  static const ItemType values[] = {
    ItemType_None,
    ItemType_Weapon,
    ItemType_Armor,
    ItemType_Accessory,
    ItemType_Consumable,
    ItemType_Material,
    ItemType_QuestItem,
    ItemType_Skillbook,
    ItemType_Blueprint,
    ItemType_Relic,
    ItemType_EnchantStone,
    ItemType_Mount,
    ItemType_Pet,
    ItemType_Misc
  };
  return values;
}

inline const char * const *EnumNamesItemType() {
  static const char * const names[15] = {
    "None",
    "Weapon",
    "Armor",
    "Accessory",
    "Consumable",
    "Material",
    "QuestItem",
    "Skillbook",
    "Blueprint",
    "Relic",
    "EnchantStone",
    "Mount",
    "Pet",
    "Misc",
    nullptr
  };
  return names;
}

inline const char *EnumNameItemType(ItemType e) {
  if (::flatbuffers::IsOutRange(e, ItemType_None, ItemType_Misc)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesItemType()[index];
}

inline bool EnumStringItemType(const char* const str, ItemType e) {
  std::size_t count = static_cast<std::size_t>(ItemType_Misc);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesItemType()[i] == str) { e = static_cast<ItemType>(i); return true; }
  }
  return false;
}

enum WeaponType : int32_t {
  WeaponType_None = 0,
  WeaponType_Sword = 1,
  WeaponType_TwoHandSword = 2,
  WeaponType_Axe = 3,
  WeaponType_TwoHandAxe = 4,
  WeaponType_Mace = 5,
  WeaponType_TwoHandMace = 6,
  WeaponType_Spear = 7,
  WeaponType_Dagger = 8,
  WeaponType_Katana = 9,
  WeaponType_Scythe = 10,
  WeaponType_Staff = 11,
  WeaponType_Wand = 12,
  WeaponType_Tome = 13,
  WeaponType_Bow = 14,
  WeaponType_Crossbow = 15,
  WeaponType_Shield = 16,
  WeaponType_MIN = WeaponType_None,
  WeaponType_MAX = WeaponType_Shield
};

inline const WeaponType (&EnumValuesWeaponType())[17] {
  static const WeaponType values[] = {
    WeaponType_None,
    WeaponType_Sword,
    WeaponType_TwoHandSword,
    WeaponType_Axe,
    WeaponType_TwoHandAxe,
    WeaponType_Mace,
    WeaponType_TwoHandMace,
    WeaponType_Spear,
    WeaponType_Dagger,
    WeaponType_Katana,
    WeaponType_Scythe,
    WeaponType_Staff,
    WeaponType_Wand,
    WeaponType_Tome,
    WeaponType_Bow,
    WeaponType_Crossbow,
    WeaponType_Shield
  };
  return values;
}

inline const char * const *EnumNamesWeaponType() {
  static const char * const names[18] = {
    "None",
    "Sword",
    "TwoHandSword",
    "Axe",
    "TwoHandAxe",
    "Mace",
    "TwoHandMace",
    "Spear",
    "Dagger",
    "Katana",
    "Scythe",
    "Staff",
    "Wand",
    "Tome",
    "Bow",
    "Crossbow",
    "Shield",
    nullptr
  };
  return names;
}

inline const char *EnumNameWeaponType(WeaponType e) {
  if (::flatbuffers::IsOutRange(e, WeaponType_None, WeaponType_Shield)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWeaponType()[index];
}

inline bool EnumStringWeaponType(const char* const str, WeaponType e) {
  std::size_t count = static_cast<std::size_t>(WeaponType_Shield);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesWeaponType()[i] == str) { e = static_cast<WeaponType>(i); return true; }
  }
  return false;
}

enum ArmorType : int32_t {
  ArmorType_None = 0,
  ArmorType_HeavyArmor = 1,
  ArmorType_MediumArmor = 2,
  ArmorType_LightArmor = 3,
  ArmorType_Robe = 4,
  ArmorType_Cloth = 5,
  ArmorType_MIN = ArmorType_None,
  ArmorType_MAX = ArmorType_Cloth
};

inline const ArmorType (&EnumValuesArmorType())[6] {
  static const ArmorType values[] = {
    ArmorType_None,
    ArmorType_HeavyArmor,
    ArmorType_MediumArmor,
    ArmorType_LightArmor,
    ArmorType_Robe,
    ArmorType_Cloth
  };
  return values;
}

inline const char * const *EnumNamesArmorType() {
  static const char * const names[7] = {
    "None",
    "HeavyArmor",
    "MediumArmor",
    "LightArmor",
    "Robe",
    "Cloth",
    nullptr
  };
  return names;
}

inline const char *EnumNameArmorType(ArmorType e) {
  if (::flatbuffers::IsOutRange(e, ArmorType_None, ArmorType_Cloth)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesArmorType()[index];
}

inline bool EnumStringArmorType(const char* const str, ArmorType e) {
  std::size_t count = static_cast<std::size_t>(ArmorType_Cloth);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesArmorType()[i] == str) { e = static_cast<ArmorType>(i); return true; }
  }
  return false;
}

enum MoveType : int32_t {
  MoveType_Walk = 0,
  MoveType_Run = 1,
  MoveType_Teleport = 2,
  MoveType_Knockback = 3,
  MoveType_MIN = MoveType_Walk,
  MoveType_MAX = MoveType_Knockback
};

inline const MoveType (&EnumValuesMoveType())[4] {
  static const MoveType values[] = {
    MoveType_Walk,
    MoveType_Run,
    MoveType_Teleport,
    MoveType_Knockback
  };
  return values;
}

inline const char * const *EnumNamesMoveType() {
  static const char * const names[5] = {
    "Walk",
    "Run",
    "Teleport",
    "Knockback",
    nullptr
  };
  return names;
}

inline const char *EnumNameMoveType(MoveType e) {
  if (::flatbuffers::IsOutRange(e, MoveType_Walk, MoveType_Knockback)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMoveType()[index];
}

inline bool EnumStringMoveType(const char* const str, MoveType e) {
  std::size_t count = static_cast<std::size_t>(MoveType_Knockback);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesMoveType()[i] == str) { e = static_cast<MoveType>(i); return true; }
  }
  return false;
}

enum MapType : int32_t {
  MapType_Town = 0,
  MapType_Field = 1,
  MapType_Dungeon = 2,
  MapType_Raid = 3,
  MapType_PvP = 4,
  MapType_Instance = 5,
  MapType_MIN = MapType_Town,
  MapType_MAX = MapType_Instance
};

inline const MapType (&EnumValuesMapType())[6] {
  static const MapType values[] = {
    MapType_Town,
    MapType_Field,
    MapType_Dungeon,
    MapType_Raid,
    MapType_PvP,
    MapType_Instance
  };
  return values;
}

inline const char * const *EnumNamesMapType() {
  static const char * const names[7] = {
    "Town",
    "Field",
    "Dungeon",
    "Raid",
    "PvP",
    "Instance",
    nullptr
  };
  return names;
}

inline const char *EnumNameMapType(MapType e) {
  if (::flatbuffers::IsOutRange(e, MapType_Town, MapType_Instance)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMapType()[index];
}

inline bool EnumStringMapType(const char* const str, MapType e) {
  std::size_t count = static_cast<std::size_t>(MapType_Instance);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesMapType()[i] == str) { e = static_cast<MapType>(i); return true; }
  }
  return false;
}

enum MonsterFaction : int32_t {
  MonsterFaction_None = 0,
  MonsterFaction_WolfPack = 1,
  MonsterFaction_GoblinTribe = 2,
  MonsterFaction_OrcClan = 3,
  MonsterFaction_UndeadLegion = 4,
  MonsterFaction_ForestSpirit = 5,
  MonsterFaction_DragonKind = 6,
  MonsterFaction_MIN = MonsterFaction_None,
  MonsterFaction_MAX = MonsterFaction_DragonKind
};

inline const MonsterFaction (&EnumValuesMonsterFaction())[7] {
  static const MonsterFaction values[] = {
    MonsterFaction_None,
    MonsterFaction_WolfPack,
    MonsterFaction_GoblinTribe,
    MonsterFaction_OrcClan,
    MonsterFaction_UndeadLegion,
    MonsterFaction_ForestSpirit,
    MonsterFaction_DragonKind
  };
  return values;
}

inline const char * const *EnumNamesMonsterFaction() {
  static const char * const names[8] = {
    "None",
    "WolfPack",
    "GoblinTribe",
    "OrcClan",
    "UndeadLegion",
    "ForestSpirit",
    "DragonKind",
    nullptr
  };
  return names;
}

inline const char *EnumNameMonsterFaction(MonsterFaction e) {
  if (::flatbuffers::IsOutRange(e, MonsterFaction_None, MonsterFaction_DragonKind)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMonsterFaction()[index];
}

inline bool EnumStringMonsterFaction(const char* const str, MonsterFaction e) {
  std::size_t count = static_cast<std::size_t>(MonsterFaction_DragonKind);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesMonsterFaction()[i] == str) { e = static_cast<MonsterFaction>(i); return true; }
  }
  return false;
}

enum JobType : int32_t {
  JobType_None = 0,
  JobType_Warrior = 101,
  JobType_Berserker = 102,
  JobType_Knight = 103,
  JobType_Paladin = 104,
  JobType_DarkKnight = 105,
  JobType_Priest = 201,
  JobType_Bishop = 202,
  JobType_SoulKeeper = 203,
  JobType_Necromancer = 204,
  JobType_Wizard = 301,
  JobType_Pyromancer = 302,
  JobType_Cryomancer = 303,
  JobType_Stormcaller = 304,
  JobType_Geomancer = 305,
  JobType_Ranger = 401,
  JobType_Hunter = 402,
  JobType_Assassin = 403,
  JobType_ShadowBlade = 404,
  JobType_Druid = 501,
  JobType_Summoner = 502,
  JobType_Bard = 503,
  JobType_Alchemist = 504,
  JobType_MIN = JobType_None,
  JobType_MAX = JobType_Alchemist
};

inline const JobType (&EnumValuesJobType())[23] {
  static const JobType values[] = {
    JobType_None,
    JobType_Warrior,
    JobType_Berserker,
    JobType_Knight,
    JobType_Paladin,
    JobType_DarkKnight,
    JobType_Priest,
    JobType_Bishop,
    JobType_SoulKeeper,
    JobType_Necromancer,
    JobType_Wizard,
    JobType_Pyromancer,
    JobType_Cryomancer,
    JobType_Stormcaller,
    JobType_Geomancer,
    JobType_Ranger,
    JobType_Hunter,
    JobType_Assassin,
    JobType_ShadowBlade,
    JobType_Druid,
    JobType_Summoner,
    JobType_Bard,
    JobType_Alchemist
  };
  return values;
}

inline const char *EnumNameJobType(JobType e) {
  switch (e) {
    case JobType_None: return "None";
    case JobType_Warrior: return "Warrior";
    case JobType_Berserker: return "Berserker";
    case JobType_Knight: return "Knight";
    case JobType_Paladin: return "Paladin";
    case JobType_DarkKnight: return "DarkKnight";
    case JobType_Priest: return "Priest";
    case JobType_Bishop: return "Bishop";
    case JobType_SoulKeeper: return "SoulKeeper";
    case JobType_Necromancer: return "Necromancer";
    case JobType_Wizard: return "Wizard";
    case JobType_Pyromancer: return "Pyromancer";
    case JobType_Cryomancer: return "Cryomancer";
    case JobType_Stormcaller: return "Stormcaller";
    case JobType_Geomancer: return "Geomancer";
    case JobType_Ranger: return "Ranger";
    case JobType_Hunter: return "Hunter";
    case JobType_Assassin: return "Assassin";
    case JobType_ShadowBlade: return "ShadowBlade";
    case JobType_Druid: return "Druid";
    case JobType_Summoner: return "Summoner";
    case JobType_Bard: return "Bard";
    case JobType_Alchemist: return "Alchemist";
    default: return "";
  }
}

inline bool EnumStringJobType(const char* const str, JobType e) {
  if(0 == strcmp(str, "None")) { e = JobType_None; return true; }
  if(0 == strcmp(str, "Warrior")) { e = JobType_Warrior; return true; }
  if(0 == strcmp(str, "Berserker")) { e = JobType_Berserker; return true; }
  if(0 == strcmp(str, "Knight")) { e = JobType_Knight; return true; }
  if(0 == strcmp(str, "Paladin")) { e = JobType_Paladin; return true; }
  if(0 == strcmp(str, "DarkKnight")) { e = JobType_DarkKnight; return true; }
  if(0 == strcmp(str, "Priest")) { e = JobType_Priest; return true; }
  if(0 == strcmp(str, "Bishop")) { e = JobType_Bishop; return true; }
  if(0 == strcmp(str, "SoulKeeper")) { e = JobType_SoulKeeper; return true; }
  if(0 == strcmp(str, "Necromancer")) { e = JobType_Necromancer; return true; }
  if(0 == strcmp(str, "Wizard")) { e = JobType_Wizard; return true; }
  if(0 == strcmp(str, "Pyromancer")) { e = JobType_Pyromancer; return true; }
  if(0 == strcmp(str, "Cryomancer")) { e = JobType_Cryomancer; return true; }
  if(0 == strcmp(str, "Stormcaller")) { e = JobType_Stormcaller; return true; }
  if(0 == strcmp(str, "Geomancer")) { e = JobType_Geomancer; return true; }
  if(0 == strcmp(str, "Ranger")) { e = JobType_Ranger; return true; }
  if(0 == strcmp(str, "Hunter")) { e = JobType_Hunter; return true; }
  if(0 == strcmp(str, "Assassin")) { e = JobType_Assassin; return true; }
  if(0 == strcmp(str, "ShadowBlade")) { e = JobType_ShadowBlade; return true; }
  if(0 == strcmp(str, "Druid")) { e = JobType_Druid; return true; }
  if(0 == strcmp(str, "Summoner")) { e = JobType_Summoner; return true; }
  if(0 == strcmp(str, "Bard")) { e = JobType_Bard; return true; }
  if(0 == strcmp(str, "Alchemist")) { e = JobType_Alchemist; return true; }
  return false;
}

enum SkillType : int32_t {
  SkillType_Active = 0,
  SkillType_Passive = 1,
  SkillType_Ultimate = 2,
  SkillType_Toggle = 3,
  SkillType_Reaction = 4,
  SkillType_MIN = SkillType_Active,
  SkillType_MAX = SkillType_Reaction
};

inline const SkillType (&EnumValuesSkillType())[5] {
  static const SkillType values[] = {
    SkillType_Active,
    SkillType_Passive,
    SkillType_Ultimate,
    SkillType_Toggle,
    SkillType_Reaction
  };
  return values;
}

inline const char * const *EnumNamesSkillType() {
  static const char * const names[6] = {
    "Active",
    "Passive",
    "Ultimate",
    "Toggle",
    "Reaction",
    nullptr
  };
  return names;
}

inline const char *EnumNameSkillType(SkillType e) {
  if (::flatbuffers::IsOutRange(e, SkillType_Active, SkillType_Reaction)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSkillType()[index];
}

inline bool EnumStringSkillType(const char* const str, SkillType e) {
  std::size_t count = static_cast<std::size_t>(SkillType_Reaction);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesSkillType()[i] == str) { e = static_cast<SkillType>(i); return true; }
  }
  return false;
}

enum ZoneAttributeType : int32_t {
  ZoneAttributeType_Neutral = 0,
  ZoneAttributeType_Holy = 1,
  ZoneAttributeType_Dark = 2,
  ZoneAttributeType_Fire = 3,
  ZoneAttributeType_Ice = 4,
  ZoneAttributeType_Lightning = 5,
  ZoneAttributeType_Earth = 6,
  ZoneAttributeType_Cursed = 7,
  ZoneAttributeType_Sacred = 8,
  ZoneAttributeType_MIN = ZoneAttributeType_Neutral,
  ZoneAttributeType_MAX = ZoneAttributeType_Sacred
};

inline const ZoneAttributeType (&EnumValuesZoneAttributeType())[9] {
  static const ZoneAttributeType values[] = {
    ZoneAttributeType_Neutral,
    ZoneAttributeType_Holy,
    ZoneAttributeType_Dark,
    ZoneAttributeType_Fire,
    ZoneAttributeType_Ice,
    ZoneAttributeType_Lightning,
    ZoneAttributeType_Earth,
    ZoneAttributeType_Cursed,
    ZoneAttributeType_Sacred
  };
  return values;
}

inline const char * const *EnumNamesZoneAttributeType() {
  static const char * const names[10] = {
    "Neutral",
    "Holy",
    "Dark",
    "Fire",
    "Ice",
    "Lightning",
    "Earth",
    "Cursed",
    "Sacred",
    nullptr
  };
  return names;
}

inline const char *EnumNameZoneAttributeType(ZoneAttributeType e) {
  if (::flatbuffers::IsOutRange(e, ZoneAttributeType_Neutral, ZoneAttributeType_Sacred)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesZoneAttributeType()[index];
}

inline bool EnumStringZoneAttributeType(const char* const str, ZoneAttributeType e) {
  std::size_t count = static_cast<std::size_t>(ZoneAttributeType_Sacred);
  for (std::size_t i=0; i<=count; ++i) {
    if (EnumNamesZoneAttributeType()[i] == str) { e = static_cast<ZoneAttributeType>(i); return true; }
  }
  return false;
}

}  // namespace makga

#endif  // FLATBUFFERS_GENERATED_ENUM_MAKGA_H_
