// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUM_MAKGA_H_
#define FLATBUFFERS_GENERATED_ENUM_MAKGA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "version_generated.h"

namespace makga {

enum class ServerType : int32_t {
  Billing = 0,
  Login = 1,
  World = 2,
  Community = 3,
  DBAgent = 4,
  Game = 5,
  Instance = 6,
  Web = 7,
  Log = 8,
  MIN = Billing,
  MAX = Log
};

inline const ServerType (&EnumValuesServerType())[9] {
  static const ServerType values[] = {
    ServerType::Billing,
    ServerType::Login,
    ServerType::World,
    ServerType::Community,
    ServerType::DBAgent,
    ServerType::Game,
    ServerType::Instance,
    ServerType::Web,
    ServerType::Log
  };
  return values;
}

inline const char * const *EnumNamesServerType() {
  static const char * const names[10] = {
    "Billing",
    "Login",
    "World",
    "Community",
    "DBAgent",
    "Game",
    "Instance",
    "Web",
    "Log",
    nullptr
  };
  return names;
}

inline const char *EnumNameServerType(ServerType e) {
  if (::flatbuffers::IsOutRange(e, ServerType::Billing, ServerType::Log)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesServerType()[index];
}

enum class DatabaseType : int32_t {
  NONE = 0,
  MIN = NONE,
  MAX = NONE
};

inline const DatabaseType (&EnumValuesDatabaseType())[1] {
  static const DatabaseType values[] = {
    DatabaseType::NONE
  };
  return values;
}

inline const char * const *EnumNamesDatabaseType() {
  static const char * const names[2] = {
    "NONE",
    nullptr
  };
  return names;
}

inline const char *EnumNameDatabaseType(DatabaseType e) {
  if (::flatbuffers::IsOutRange(e, DatabaseType::NONE, DatabaseType::NONE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDatabaseType()[index];
}

enum class RedisType : int32_t {
  NONE = 0,
  MIN = NONE,
  MAX = NONE
};

inline const RedisType (&EnumValuesRedisType())[1] {
  static const RedisType values[] = {
    RedisType::NONE
  };
  return values;
}

inline const char * const *EnumNamesRedisType() {
  static const char * const names[2] = {
    "NONE",
    nullptr
  };
  return names;
}

inline const char *EnumNameRedisType(RedisType e) {
  if (::flatbuffers::IsOutRange(e, RedisType::NONE, RedisType::NONE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRedisType()[index];
}

enum class AccountType : int32_t {
  NONE = 0,
  MIN = NONE,
  MAX = NONE
};

inline const AccountType (&EnumValuesAccountType())[1] {
  static const AccountType values[] = {
    AccountType::NONE
  };
  return values;
}

inline const char * const *EnumNamesAccountType() {
  static const char * const names[2] = {
    "NONE",
    nullptr
  };
  return names;
}

inline const char *EnumNameAccountType(AccountType e) {
  if (::flatbuffers::IsOutRange(e, AccountType::NONE, AccountType::NONE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAccountType()[index];
}

enum class SessionType : int32_t {
  None = 0,
  User = 1,
  MIN = None,
  MAX = User
};

inline const SessionType (&EnumValuesSessionType())[2] {
  static const SessionType values[] = {
    SessionType::None,
    SessionType::User
  };
  return values;
}

inline const char * const *EnumNamesSessionType() {
  static const char * const names[3] = {
    "None",
    "User",
    nullptr
  };
  return names;
}

inline const char *EnumNameSessionType(SessionType e) {
  if (::flatbuffers::IsOutRange(e, SessionType::None, SessionType::User)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSessionType()[index];
}

enum class MessageType : int32_t {
  GridAddActor = 0,
  GridRemoveActor = 1,
  GridBroadcastMove = 2,
  TerrainRegisterActor = 3,
  TerrainUnregisterActor = 4,
  ActorRequestMove = 5,
  ActorSetTarget = 6,
  ActorSetLeader = 7,
  ActorSetOwner = 8,
  ActorDelete = 9,
  ActorAttack = 10,
  ActorAttackResponse = 11,
  ActorMoveResponse = 12,
  ActorSee = 13,
  CharacterSpawn = 14,
  CharacterDespawn = 15,
  MonsterSpawn = 16,
  MonsterDespawn = 17,
  MonsterAggravate = 18,
  CharacterReceiveLoot = 19,
  MIN = GridAddActor,
  MAX = CharacterReceiveLoot
};

inline const MessageType (&EnumValuesMessageType())[20] {
  static const MessageType values[] = {
    MessageType::GridAddActor,
    MessageType::GridRemoveActor,
    MessageType::GridBroadcastMove,
    MessageType::TerrainRegisterActor,
    MessageType::TerrainUnregisterActor,
    MessageType::ActorRequestMove,
    MessageType::ActorSetTarget,
    MessageType::ActorSetLeader,
    MessageType::ActorSetOwner,
    MessageType::ActorDelete,
    MessageType::ActorAttack,
    MessageType::ActorAttackResponse,
    MessageType::ActorMoveResponse,
    MessageType::ActorSee,
    MessageType::CharacterSpawn,
    MessageType::CharacterDespawn,
    MessageType::MonsterSpawn,
    MessageType::MonsterDespawn,
    MessageType::MonsterAggravate,
    MessageType::CharacterReceiveLoot
  };
  return values;
}

inline const char * const *EnumNamesMessageType() {
  static const char * const names[21] = {
    "GridAddActor",
    "GridRemoveActor",
    "GridBroadcastMove",
    "TerrainRegisterActor",
    "TerrainUnregisterActor",
    "ActorRequestMove",
    "ActorSetTarget",
    "ActorSetLeader",
    "ActorSetOwner",
    "ActorDelete",
    "ActorAttack",
    "ActorAttackResponse",
    "ActorMoveResponse",
    "ActorSee",
    "CharacterSpawn",
    "CharacterDespawn",
    "MonsterSpawn",
    "MonsterDespawn",
    "MonsterAggravate",
    "CharacterReceiveLoot",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageType(MessageType e) {
  if (::flatbuffers::IsOutRange(e, MessageType::GridAddActor, MessageType::CharacterReceiveLoot)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageType()[index];
}

enum class TickGroup : int32_t {
  PrePhysics = 0,
  Physics = 1,
  PostPhysics = 2,
  PostUpdate = 3,
  Max = 4,
  MIN = PrePhysics,
  MAX = Max
};

inline const TickGroup (&EnumValuesTickGroup())[5] {
  static const TickGroup values[] = {
    TickGroup::PrePhysics,
    TickGroup::Physics,
    TickGroup::PostPhysics,
    TickGroup::PostUpdate,
    TickGroup::Max
  };
  return values;
}

inline const char * const *EnumNamesTickGroup() {
  static const char * const names[6] = {
    "PrePhysics",
    "Physics",
    "PostPhysics",
    "PostUpdate",
    "Max",
    nullptr
  };
  return names;
}

inline const char *EnumNameTickGroup(TickGroup e) {
  if (::flatbuffers::IsOutRange(e, TickGroup::PrePhysics, TickGroup::Max)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTickGroup()[index];
}

enum class AIType : int32_t {
  Aggressive = 0,
  NonAggressive = 1,
  Coward = 2,
  FieldBoss = 3,
  InstanceBoss = 4,
  Character = 5,
  Sandbag = 6,
  MIN = Aggressive,
  MAX = Sandbag
};

inline const AIType (&EnumValuesAIType())[7] {
  static const AIType values[] = {
    AIType::Aggressive,
    AIType::NonAggressive,
    AIType::Coward,
    AIType::FieldBoss,
    AIType::InstanceBoss,
    AIType::Character,
    AIType::Sandbag
  };
  return values;
}

inline const char * const *EnumNamesAIType() {
  static const char * const names[8] = {
    "Aggressive",
    "NonAggressive",
    "Coward",
    "FieldBoss",
    "InstanceBoss",
    "Character",
    "Sandbag",
    nullptr
  };
  return names;
}

inline const char *EnumNameAIType(AIType e) {
  if (::flatbuffers::IsOutRange(e, AIType::Aggressive, AIType::Sandbag)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAIType()[index];
}

enum class ActorType : int32_t {
  None = 0,
  Character = 1,
  Monster = 2,
  Gadget = 3,
  Object = 4,
  MIN = None,
  MAX = Object
};

inline const ActorType (&EnumValuesActorType())[5] {
  static const ActorType values[] = {
    ActorType::None,
    ActorType::Character,
    ActorType::Monster,
    ActorType::Gadget,
    ActorType::Object
  };
  return values;
}

inline const char * const *EnumNamesActorType() {
  static const char * const names[6] = {
    "None",
    "Character",
    "Monster",
    "Gadget",
    "Object",
    nullptr
  };
  return names;
}

inline const char *EnumNameActorType(ActorType e) {
  if (::flatbuffers::IsOutRange(e, ActorType::None, ActorType::Object)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesActorType()[index];
}

enum class CityType : int32_t {
  NONE = 0,
  MIN = NONE,
  MAX = NONE
};

inline const CityType (&EnumValuesCityType())[1] {
  static const CityType values[] = {
    CityType::NONE
  };
  return values;
}

inline const char * const *EnumNamesCityType() {
  static const char * const names[2] = {
    "NONE",
    nullptr
  };
  return names;
}

inline const char *EnumNameCityType(CityType e) {
  if (::flatbuffers::IsOutRange(e, CityType::NONE, CityType::NONE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCityType()[index];
}

enum class PkType : int32_t {
  Safe = 0,
  Lawful = 1,
  Conflict = 2,
  Hostile = 3,
  Arena = 4,
  MIN = Safe,
  MAX = Arena
};

inline const PkType (&EnumValuesPkType())[5] {
  static const PkType values[] = {
    PkType::Safe,
    PkType::Lawful,
    PkType::Conflict,
    PkType::Hostile,
    PkType::Arena
  };
  return values;
}

inline const char * const *EnumNamesPkType() {
  static const char * const names[6] = {
    "Safe",
    "Lawful",
    "Conflict",
    "Hostile",
    "Arena",
    nullptr
  };
  return names;
}

inline const char *EnumNamePkType(PkType e) {
  if (::flatbuffers::IsOutRange(e, PkType::Safe, PkType::Arena)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPkType()[index];
}

enum class AreaType : int32_t {
  City = 0,
  Village = 1,
  Field = 2,
  Instance = 3,
  MIN = City,
  MAX = Instance
};

inline const AreaType (&EnumValuesAreaType())[4] {
  static const AreaType values[] = {
    AreaType::City,
    AreaType::Village,
    AreaType::Field,
    AreaType::Instance
  };
  return values;
}

inline const char * const *EnumNamesAreaType() {
  static const char * const names[5] = {
    "City",
    "Village",
    "Field",
    "Instance",
    nullptr
  };
  return names;
}

inline const char *EnumNameAreaType(AreaType e) {
  if (::flatbuffers::IsOutRange(e, AreaType::City, AreaType::Instance)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAreaType()[index];
}

enum class AttributeType : int32_t {
  None = 0,
  Fire = 1,
  Water = 2,
  Wind = 3,
  Earth = 4,
  Holy = 5,
  Dark = 6,
  MIN = None,
  MAX = Dark
};

inline const AttributeType (&EnumValuesAttributeType())[7] {
  static const AttributeType values[] = {
    AttributeType::None,
    AttributeType::Fire,
    AttributeType::Water,
    AttributeType::Wind,
    AttributeType::Earth,
    AttributeType::Holy,
    AttributeType::Dark
  };
  return values;
}

inline const char * const *EnumNamesAttributeType() {
  static const char * const names[8] = {
    "None",
    "Fire",
    "Water",
    "Wind",
    "Earth",
    "Holy",
    "Dark",
    nullptr
  };
  return names;
}

inline const char *EnumNameAttributeType(AttributeType e) {
  if (::flatbuffers::IsOutRange(e, AttributeType::None, AttributeType::Dark)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAttributeType()[index];
}

enum class RaceType : int32_t {
  Human = 0,
  Elf = 1,
  Dwarf = 2,
  Orc = 3,
  Undead = 4,
  Dragon = 5,
  MIN = Human,
  MAX = Dragon
};

inline const RaceType (&EnumValuesRaceType())[6] {
  static const RaceType values[] = {
    RaceType::Human,
    RaceType::Elf,
    RaceType::Dwarf,
    RaceType::Orc,
    RaceType::Undead,
    RaceType::Dragon
  };
  return values;
}

inline const char * const *EnumNamesRaceType() {
  static const char * const names[7] = {
    "Human",
    "Elf",
    "Dwarf",
    "Orc",
    "Undead",
    "Dragon",
    nullptr
  };
  return names;
}

inline const char *EnumNameRaceType(RaceType e) {
  if (::flatbuffers::IsOutRange(e, RaceType::Human, RaceType::Dragon)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRaceType()[index];
}

enum class CurrencyType : int32_t {
  Gold = 0,
  Ruby = 1,
  Mileage = 2,
  Honor = 3,
  GuildPoint = 4,
  MIN = Gold,
  MAX = GuildPoint
};

inline const CurrencyType (&EnumValuesCurrencyType())[5] {
  static const CurrencyType values[] = {
    CurrencyType::Gold,
    CurrencyType::Ruby,
    CurrencyType::Mileage,
    CurrencyType::Honor,
    CurrencyType::GuildPoint
  };
  return values;
}

inline const char * const *EnumNamesCurrencyType() {
  static const char * const names[6] = {
    "Gold",
    "Ruby",
    "Mileage",
    "Honor",
    "GuildPoint",
    nullptr
  };
  return names;
}

inline const char *EnumNameCurrencyType(CurrencyType e) {
  if (::flatbuffers::IsOutRange(e, CurrencyType::Gold, CurrencyType::GuildPoint)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCurrencyType()[index];
}

enum class GradeType : int32_t {
  Normal = 0,
  Magic = 1,
  Rare = 2,
  Unique = 3,
  Epic = 4,
  Legendary = 5,
  Mythic = 6,
  MIN = Normal,
  MAX = Mythic
};

inline const GradeType (&EnumValuesGradeType())[7] {
  static const GradeType values[] = {
    GradeType::Normal,
    GradeType::Magic,
    GradeType::Rare,
    GradeType::Unique,
    GradeType::Epic,
    GradeType::Legendary,
    GradeType::Mythic
  };
  return values;
}

inline const char * const *EnumNamesGradeType() {
  static const char * const names[8] = {
    "Normal",
    "Magic",
    "Rare",
    "Unique",
    "Epic",
    "Legendary",
    "Mythic",
    nullptr
  };
  return names;
}

inline const char *EnumNameGradeType(GradeType e) {
  if (::flatbuffers::IsOutRange(e, GradeType::Normal, GradeType::Mythic)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGradeType()[index];
}

enum class StatType : int32_t {
  Strength = 0,
  Agility = 1,
  Intelligence = 2,
  Stamina = 3,
  Dexterity = 4,
  Wisdom = 5,
  Luck = 6,
  Constitution = 7,
  Spirit = 8,
  Charisma = 9,
  Hp = 10,
  Mp = 11,
  HpRegen = 12,
  MpRegen = 13,
  AttackSpeed = 14,
  CastSpeed = 15,
  MoveSpeed = 16,
  Accuracy = 17,
  Penetration = 18,
  MagicPenetration = 19,
  SkillDamage = 20,
  BonusDamage = 21,
  DamageReduction = 22,
  BossDamage = 23,
  PhysicalAtk = 24,
  PhysicalDef = 25,
  MagicalAtk = 26,
  MagicalDef = 27,
  FireDamage = 28,
  FireReduction = 29,
  WaterDamage = 30,
  WaterReduction = 31,
  WindDamage = 32,
  WindReduction = 33,
  EarthDamage = 34,
  EarthReduction = 35,
  HolyDamage = 36,
  HolyReduction = 37,
  DarkDamage = 38,
  DarkReduction = 39,
  CriRate = 40,
  CriResist = 41,
  CriDamage = 42,
  CriReduction = 43,
  BlockRate = 44,
  BlockResist = 45,
  MIN = Strength,
  MAX = BlockResist
};

inline const StatType (&EnumValuesStatType())[46] {
  static const StatType values[] = {
    StatType::Strength,
    StatType::Agility,
    StatType::Intelligence,
    StatType::Stamina,
    StatType::Dexterity,
    StatType::Wisdom,
    StatType::Luck,
    StatType::Constitution,
    StatType::Spirit,
    StatType::Charisma,
    StatType::Hp,
    StatType::Mp,
    StatType::HpRegen,
    StatType::MpRegen,
    StatType::AttackSpeed,
    StatType::CastSpeed,
    StatType::MoveSpeed,
    StatType::Accuracy,
    StatType::Penetration,
    StatType::MagicPenetration,
    StatType::SkillDamage,
    StatType::BonusDamage,
    StatType::DamageReduction,
    StatType::BossDamage,
    StatType::PhysicalAtk,
    StatType::PhysicalDef,
    StatType::MagicalAtk,
    StatType::MagicalDef,
    StatType::FireDamage,
    StatType::FireReduction,
    StatType::WaterDamage,
    StatType::WaterReduction,
    StatType::WindDamage,
    StatType::WindReduction,
    StatType::EarthDamage,
    StatType::EarthReduction,
    StatType::HolyDamage,
    StatType::HolyReduction,
    StatType::DarkDamage,
    StatType::DarkReduction,
    StatType::CriRate,
    StatType::CriResist,
    StatType::CriDamage,
    StatType::CriReduction,
    StatType::BlockRate,
    StatType::BlockResist
  };
  return values;
}

inline const char * const *EnumNamesStatType() {
  static const char * const names[47] = {
    "Strength",
    "Agility",
    "Intelligence",
    "Stamina",
    "Dexterity",
    "Wisdom",
    "Luck",
    "Constitution",
    "Spirit",
    "Charisma",
    "Hp",
    "Mp",
    "HpRegen",
    "MpRegen",
    "AttackSpeed",
    "CastSpeed",
    "MoveSpeed",
    "Accuracy",
    "Penetration",
    "MagicPenetration",
    "SkillDamage",
    "BonusDamage",
    "DamageReduction",
    "BossDamage",
    "PhysicalAtk",
    "PhysicalDef",
    "MagicalAtk",
    "MagicalDef",
    "FireDamage",
    "FireReduction",
    "WaterDamage",
    "WaterReduction",
    "WindDamage",
    "WindReduction",
    "EarthDamage",
    "EarthReduction",
    "HolyDamage",
    "HolyReduction",
    "DarkDamage",
    "DarkReduction",
    "CriRate",
    "CriResist",
    "CriDamage",
    "CriReduction",
    "BlockRate",
    "BlockResist",
    nullptr
  };
  return names;
}

inline const char *EnumNameStatType(StatType e) {
  if (::flatbuffers::IsOutRange(e, StatType::Strength, StatType::BlockResist)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStatType()[index];
}

enum class AbilityType : int32_t {
  Stun = 0,
  Knockback = 1,
  Slow = 2,
  Provoke = 3,
  Silence = 4,
  Blessing = 5,
  DoubleHitChance = 6,
  IgnoreShield = 7,
  LifeSteal = 8,
  Shield = 9,
  HealingUp = 10,
  CoolTimeDown = 11,
  Burn = 12,
  Curse = 13,
  Immortal = 14,
  MIN = Stun,
  MAX = Immortal
};

inline const AbilityType (&EnumValuesAbilityType())[15] {
  static const AbilityType values[] = {
    AbilityType::Stun,
    AbilityType::Knockback,
    AbilityType::Slow,
    AbilityType::Provoke,
    AbilityType::Silence,
    AbilityType::Blessing,
    AbilityType::DoubleHitChance,
    AbilityType::IgnoreShield,
    AbilityType::LifeSteal,
    AbilityType::Shield,
    AbilityType::HealingUp,
    AbilityType::CoolTimeDown,
    AbilityType::Burn,
    AbilityType::Curse,
    AbilityType::Immortal
  };
  return values;
}

inline const char * const *EnumNamesAbilityType() {
  static const char * const names[16] = {
    "Stun",
    "Knockback",
    "Slow",
    "Provoke",
    "Silence",
    "Blessing",
    "DoubleHitChance",
    "IgnoreShield",
    "LifeSteal",
    "Shield",
    "HealingUp",
    "CoolTimeDown",
    "Burn",
    "Curse",
    "Immortal",
    nullptr
  };
  return names;
}

inline const char *EnumNameAbilityType(AbilityType e) {
  if (::flatbuffers::IsOutRange(e, AbilityType::Stun, AbilityType::Immortal)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAbilityType()[index];
}

enum class TargetingType : int32_t {
  Self = 0,
  Unit = 1,
  Ground = 2,
  MIN = Self,
  MAX = Ground
};

inline const TargetingType (&EnumValuesTargetingType())[3] {
  static const TargetingType values[] = {
    TargetingType::Self,
    TargetingType::Unit,
    TargetingType::Ground
  };
  return values;
}

inline const char * const *EnumNamesTargetingType() {
  static const char * const names[4] = {
    "Self",
    "Unit",
    "Ground",
    nullptr
  };
  return names;
}

inline const char *EnumNameTargetingType(TargetingType e) {
  if (::flatbuffers::IsOutRange(e, TargetingType::Self, TargetingType::Ground)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTargetingType()[index];
}

enum class CostType : int32_t {
  Gold = 0,
  Hp = 1,
  Mp = 2,
  MIN = Gold,
  MAX = Mp
};

inline const CostType (&EnumValuesCostType())[3] {
  static const CostType values[] = {
    CostType::Gold,
    CostType::Hp,
    CostType::Mp
  };
  return values;
}

inline const char * const *EnumNamesCostType() {
  static const char * const names[4] = {
    "Gold",
    "Hp",
    "Mp",
    nullptr
  };
  return names;
}

inline const char *EnumNameCostType(CostType e) {
  if (::flatbuffers::IsOutRange(e, CostType::Gold, CostType::Mp)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCostType()[index];
}

enum class ItemReason : int32_t {
  AddDrop = 0,
  SubUse = 1,
  MIN = AddDrop,
  MAX = SubUse
};

inline const ItemReason (&EnumValuesItemReason())[2] {
  static const ItemReason values[] = {
    ItemReason::AddDrop,
    ItemReason::SubUse
  };
  return values;
}

inline const char * const *EnumNamesItemReason() {
  static const char * const names[3] = {
    "AddDrop",
    "SubUse",
    nullptr
  };
  return names;
}

inline const char *EnumNameItemReason(ItemReason e) {
  if (::flatbuffers::IsOutRange(e, ItemReason::AddDrop, ItemReason::SubUse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesItemReason()[index];
}

enum class DamageType : int32_t {
  Physical = 0,
  Magical = 1,
  True = 2,
  Holy = 3,
  Dark = 4,
  Fire = 5,
  Ice = 6,
  Lightning = 7,
  Earth = 8,
  Bleed = 9,
  Poison = 10,
  MIN = Physical,
  MAX = Poison
};

inline const DamageType (&EnumValuesDamageType())[11] {
  static const DamageType values[] = {
    DamageType::Physical,
    DamageType::Magical,
    DamageType::True,
    DamageType::Holy,
    DamageType::Dark,
    DamageType::Fire,
    DamageType::Ice,
    DamageType::Lightning,
    DamageType::Earth,
    DamageType::Bleed,
    DamageType::Poison
  };
  return values;
}

inline const char * const *EnumNamesDamageType() {
  static const char * const names[12] = {
    "Physical",
    "Magical",
    "True",
    "Holy",
    "Dark",
    "Fire",
    "Ice",
    "Lightning",
    "Earth",
    "Bleed",
    "Poison",
    nullptr
  };
  return names;
}

inline const char *EnumNameDamageType(DamageType e) {
  if (::flatbuffers::IsOutRange(e, DamageType::Physical, DamageType::Poison)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDamageType()[index];
}

enum class MonsterType : int32_t {
  Beast = 0,
  Undead = 1,
  Demon = 2,
  Dragon = 3,
  Elemental = 4,
  HolyBeing = 5,
  DarkBeing = 6,
  Human = 7,
  Plant = 8,
  Construct = 9,
  MIN = Beast,
  MAX = Construct
};

inline const MonsterType (&EnumValuesMonsterType())[10] {
  static const MonsterType values[] = {
    MonsterType::Beast,
    MonsterType::Undead,
    MonsterType::Demon,
    MonsterType::Dragon,
    MonsterType::Elemental,
    MonsterType::HolyBeing,
    MonsterType::DarkBeing,
    MonsterType::Human,
    MonsterType::Plant,
    MonsterType::Construct
  };
  return values;
}

inline const char * const *EnumNamesMonsterType() {
  static const char * const names[11] = {
    "Beast",
    "Undead",
    "Demon",
    "Dragon",
    "Elemental",
    "HolyBeing",
    "DarkBeing",
    "Human",
    "Plant",
    "Construct",
    nullptr
  };
  return names;
}

inline const char *EnumNameMonsterType(MonsterType e) {
  if (::flatbuffers::IsOutRange(e, MonsterType::Beast, MonsterType::Construct)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMonsterType()[index];
}

enum class StatusEffectType : int32_t {
  Bleed = 0,
  Fracture = 1,
  Root = 2,
  Poison = 3,
  Freeze = 4,
  Electrify = 5,
  Ignite = 6,
  Petrify = 7,
  Blind = 8,
  Reveal = 9,
  HolyMark = 10,
  Curse = 11,
  Fear = 12,
  Decay = 13,
  DarkMark = 14,
  Stun = 15,
  Sleep = 16,
  Silence = 17,
  Slow = 18,
  Knockback = 19,
  MIN = Bleed,
  MAX = Knockback
};

inline const StatusEffectType (&EnumValuesStatusEffectType())[20] {
  static const StatusEffectType values[] = {
    StatusEffectType::Bleed,
    StatusEffectType::Fracture,
    StatusEffectType::Root,
    StatusEffectType::Poison,
    StatusEffectType::Freeze,
    StatusEffectType::Electrify,
    StatusEffectType::Ignite,
    StatusEffectType::Petrify,
    StatusEffectType::Blind,
    StatusEffectType::Reveal,
    StatusEffectType::HolyMark,
    StatusEffectType::Curse,
    StatusEffectType::Fear,
    StatusEffectType::Decay,
    StatusEffectType::DarkMark,
    StatusEffectType::Stun,
    StatusEffectType::Sleep,
    StatusEffectType::Silence,
    StatusEffectType::Slow,
    StatusEffectType::Knockback
  };
  return values;
}

inline const char * const *EnumNamesStatusEffectType() {
  static const char * const names[21] = {
    "Bleed",
    "Fracture",
    "Root",
    "Poison",
    "Freeze",
    "Electrify",
    "Ignite",
    "Petrify",
    "Blind",
    "Reveal",
    "HolyMark",
    "Curse",
    "Fear",
    "Decay",
    "DarkMark",
    "Stun",
    "Sleep",
    "Silence",
    "Slow",
    "Knockback",
    nullptr
  };
  return names;
}

inline const char *EnumNameStatusEffectType(StatusEffectType e) {
  if (::flatbuffers::IsOutRange(e, StatusEffectType::Bleed, StatusEffectType::Knockback)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStatusEffectType()[index];
}

enum class DungeonType : int32_t {
  Normal = 0,
  Solo = 1,
  Elite = 2,
  Hard = 3,
  Challenge = 4,
  Raid = 5,
  Special = 6,
  MIN = Normal,
  MAX = Special
};

inline const DungeonType (&EnumValuesDungeonType())[7] {
  static const DungeonType values[] = {
    DungeonType::Normal,
    DungeonType::Solo,
    DungeonType::Elite,
    DungeonType::Hard,
    DungeonType::Challenge,
    DungeonType::Raid,
    DungeonType::Special
  };
  return values;
}

inline const char * const *EnumNamesDungeonType() {
  static const char * const names[8] = {
    "Normal",
    "Solo",
    "Elite",
    "Hard",
    "Challenge",
    "Raid",
    "Special",
    nullptr
  };
  return names;
}

inline const char *EnumNameDungeonType(DungeonType e) {
  if (::flatbuffers::IsOutRange(e, DungeonType::Normal, DungeonType::Special)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDungeonType()[index];
}

enum class QuestType : int32_t {
  Main = 0,
  Sub = 1,
  Daily = 2,
  Weekly = 3,
  Guild = 4,
  Bounty = 5,
  ClassQuest = 6,
  Repeatable = 7,
  MIN = Main,
  MAX = Repeatable
};

inline const QuestType (&EnumValuesQuestType())[8] {
  static const QuestType values[] = {
    QuestType::Main,
    QuestType::Sub,
    QuestType::Daily,
    QuestType::Weekly,
    QuestType::Guild,
    QuestType::Bounty,
    QuestType::ClassQuest,
    QuestType::Repeatable
  };
  return values;
}

inline const char * const *EnumNamesQuestType() {
  static const char * const names[9] = {
    "Main",
    "Sub",
    "Daily",
    "Weekly",
    "Guild",
    "Bounty",
    "ClassQuest",
    "Repeatable",
    nullptr
  };
  return names;
}

inline const char *EnumNameQuestType(QuestType e) {
  if (::flatbuffers::IsOutRange(e, QuestType::Main, QuestType::Repeatable)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesQuestType()[index];
}

enum class NPCType : int32_t {
  Merchant = 0,
  QuestGiver = 1,
  Guard = 2,
  Blacksmith = 3,
  Enchanter = 4,
  Alchemist = 5,
  Trainer = 6,
  GuildMaster = 7,
  AuctionClerk = 8,
  Banker = 9,
  Teleporter = 10,
  MIN = Merchant,
  MAX = Teleporter
};

inline const NPCType (&EnumValuesNPCType())[11] {
  static const NPCType values[] = {
    NPCType::Merchant,
    NPCType::QuestGiver,
    NPCType::Guard,
    NPCType::Blacksmith,
    NPCType::Enchanter,
    NPCType::Alchemist,
    NPCType::Trainer,
    NPCType::GuildMaster,
    NPCType::AuctionClerk,
    NPCType::Banker,
    NPCType::Teleporter
  };
  return values;
}

inline const char * const *EnumNamesNPCType() {
  static const char * const names[12] = {
    "Merchant",
    "QuestGiver",
    "Guard",
    "Blacksmith",
    "Enchanter",
    "Alchemist",
    "Trainer",
    "GuildMaster",
    "AuctionClerk",
    "Banker",
    "Teleporter",
    nullptr
  };
  return names;
}

inline const char *EnumNameNPCType(NPCType e) {
  if (::flatbuffers::IsOutRange(e, NPCType::Merchant, NPCType::Teleporter)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNPCType()[index];
}

enum class CraftType : int32_t {
  Blacksmithing = 0,
  Tailoring = 1,
  Leatherwork = 2,
  Alchemy = 3,
  Cooking = 4,
  Enchanting = 5,
  Jeweling = 6,
  Inscription = 7,
  MIN = Blacksmithing,
  MAX = Inscription
};

inline const CraftType (&EnumValuesCraftType())[8] {
  static const CraftType values[] = {
    CraftType::Blacksmithing,
    CraftType::Tailoring,
    CraftType::Leatherwork,
    CraftType::Alchemy,
    CraftType::Cooking,
    CraftType::Enchanting,
    CraftType::Jeweling,
    CraftType::Inscription
  };
  return values;
}

inline const char * const *EnumNamesCraftType() {
  static const char * const names[9] = {
    "Blacksmithing",
    "Tailoring",
    "Leatherwork",
    "Alchemy",
    "Cooking",
    "Enchanting",
    "Jeweling",
    "Inscription",
    nullptr
  };
  return names;
}

inline const char *EnumNameCraftType(CraftType e) {
  if (::flatbuffers::IsOutRange(e, CraftType::Blacksmithing, CraftType::Inscription)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCraftType()[index];
}

enum class PartyRole : int32_t {
  Leader = 0,
  Member = 1,
  MIN = Leader,
  MAX = Member
};

inline const PartyRole (&EnumValuesPartyRole())[2] {
  static const PartyRole values[] = {
    PartyRole::Leader,
    PartyRole::Member
  };
  return values;
}

inline const char * const *EnumNamesPartyRole() {
  static const char * const names[3] = {
    "Leader",
    "Member",
    nullptr
  };
  return names;
}

inline const char *EnumNamePartyRole(PartyRole e) {
  if (::flatbuffers::IsOutRange(e, PartyRole::Leader, PartyRole::Member)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPartyRole()[index];
}

enum class PartyState : int32_t {
  Idle = 0,
  InDungeon = 1,
  InCombat = 2,
  MIN = Idle,
  MAX = InCombat
};

inline const PartyState (&EnumValuesPartyState())[3] {
  static const PartyState values[] = {
    PartyState::Idle,
    PartyState::InDungeon,
    PartyState::InCombat
  };
  return values;
}

inline const char * const *EnumNamesPartyState() {
  static const char * const names[4] = {
    "Idle",
    "InDungeon",
    "InCombat",
    nullptr
  };
  return names;
}

inline const char *EnumNamePartyState(PartyState e) {
  if (::flatbuffers::IsOutRange(e, PartyState::Idle, PartyState::InCombat)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPartyState()[index];
}

enum class ExpShareType : int32_t {
  Equal = 0,
  Contribution = 1,
  MIN = Equal,
  MAX = Contribution
};

inline const ExpShareType (&EnumValuesExpShareType())[2] {
  static const ExpShareType values[] = {
    ExpShareType::Equal,
    ExpShareType::Contribution
  };
  return values;
}

inline const char * const *EnumNamesExpShareType() {
  static const char * const names[3] = {
    "Equal",
    "Contribution",
    nullptr
  };
  return names;
}

inline const char *EnumNameExpShareType(ExpShareType e) {
  if (::flatbuffers::IsOutRange(e, ExpShareType::Equal, ExpShareType::Contribution)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesExpShareType()[index];
}

enum class LootType : int32_t {
  FreeForAll = 0,
  RoundRobin = 1,
  NeedGreed = 2,
  MIN = FreeForAll,
  MAX = NeedGreed
};

inline const LootType (&EnumValuesLootType())[3] {
  static const LootType values[] = {
    LootType::FreeForAll,
    LootType::RoundRobin,
    LootType::NeedGreed
  };
  return values;
}

inline const char * const *EnumNamesLootType() {
  static const char * const names[4] = {
    "FreeForAll",
    "RoundRobin",
    "NeedGreed",
    nullptr
  };
  return names;
}

inline const char *EnumNameLootType(LootType e) {
  if (::flatbuffers::IsOutRange(e, LootType::FreeForAll, LootType::NeedGreed)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLootType()[index];
}

enum class PartyGoalType : int32_t {
  Field = 0,
  Dungeon = 1,
  MIN = Field,
  MAX = Dungeon
};

inline const PartyGoalType (&EnumValuesPartyGoalType())[2] {
  static const PartyGoalType values[] = {
    PartyGoalType::Field,
    PartyGoalType::Dungeon
  };
  return values;
}

inline const char * const *EnumNamesPartyGoalType() {
  static const char * const names[3] = {
    "Field",
    "Dungeon",
    nullptr
  };
  return names;
}

inline const char *EnumNamePartyGoalType(PartyGoalType e) {
  if (::flatbuffers::IsOutRange(e, PartyGoalType::Field, PartyGoalType::Dungeon)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPartyGoalType()[index];
}

enum class EquipSlot : int32_t {
  None = 0,
  Helm = 1,
  Chest = 2,
  Legs = 3,
  Gloves = 4,
  Boots = 5,
  Cloak = 6,
  Weapon = 7,
  OffHand = 8,
  Ring1 = 9,
  Ring2 = 10,
  Necklace = 11,
  Earring = 12,
  Belt = 13,
  Relic = 14,
  MIN = None,
  MAX = Relic
};

inline const EquipSlot (&EnumValuesEquipSlot())[15] {
  static const EquipSlot values[] = {
    EquipSlot::None,
    EquipSlot::Helm,
    EquipSlot::Chest,
    EquipSlot::Legs,
    EquipSlot::Gloves,
    EquipSlot::Boots,
    EquipSlot::Cloak,
    EquipSlot::Weapon,
    EquipSlot::OffHand,
    EquipSlot::Ring1,
    EquipSlot::Ring2,
    EquipSlot::Necklace,
    EquipSlot::Earring,
    EquipSlot::Belt,
    EquipSlot::Relic
  };
  return values;
}

inline const char * const *EnumNamesEquipSlot() {
  static const char * const names[16] = {
    "None",
    "Helm",
    "Chest",
    "Legs",
    "Gloves",
    "Boots",
    "Cloak",
    "Weapon",
    "OffHand",
    "Ring1",
    "Ring2",
    "Necklace",
    "Earring",
    "Belt",
    "Relic",
    nullptr
  };
  return names;
}

inline const char *EnumNameEquipSlot(EquipSlot e) {
  if (::flatbuffers::IsOutRange(e, EquipSlot::None, EquipSlot::Relic)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEquipSlot()[index];
}

enum class ItemType : int32_t {
  None = 0,
  Weapon = 1,
  Armor = 2,
  Accessory = 3,
  Consumable = 4,
  Material = 5,
  QuestItem = 6,
  Skillbook = 7,
  Blueprint = 8,
  Relic = 9,
  EnchantStone = 10,
  Mount = 11,
  Pet = 12,
  Misc = 13,
  MIN = None,
  MAX = Misc
};

inline const ItemType (&EnumValuesItemType())[14] {
  static const ItemType values[] = {
    ItemType::None,
    ItemType::Weapon,
    ItemType::Armor,
    ItemType::Accessory,
    ItemType::Consumable,
    ItemType::Material,
    ItemType::QuestItem,
    ItemType::Skillbook,
    ItemType::Blueprint,
    ItemType::Relic,
    ItemType::EnchantStone,
    ItemType::Mount,
    ItemType::Pet,
    ItemType::Misc
  };
  return values;
}

inline const char * const *EnumNamesItemType() {
  static const char * const names[15] = {
    "None",
    "Weapon",
    "Armor",
    "Accessory",
    "Consumable",
    "Material",
    "QuestItem",
    "Skillbook",
    "Blueprint",
    "Relic",
    "EnchantStone",
    "Mount",
    "Pet",
    "Misc",
    nullptr
  };
  return names;
}

inline const char *EnumNameItemType(ItemType e) {
  if (::flatbuffers::IsOutRange(e, ItemType::None, ItemType::Misc)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesItemType()[index];
}

enum class WeaponType : int32_t {
  None = 0,
  Sword = 1,
  TwoHandSword = 2,
  Axe = 3,
  TwoHandAxe = 4,
  Mace = 5,
  TwoHandMace = 6,
  Spear = 7,
  Dagger = 8,
  Katana = 9,
  Scythe = 10,
  Staff = 11,
  Wand = 12,
  Tome = 13,
  Bow = 14,
  Crossbow = 15,
  Shield = 16,
  MIN = None,
  MAX = Shield
};

inline const WeaponType (&EnumValuesWeaponType())[17] {
  static const WeaponType values[] = {
    WeaponType::None,
    WeaponType::Sword,
    WeaponType::TwoHandSword,
    WeaponType::Axe,
    WeaponType::TwoHandAxe,
    WeaponType::Mace,
    WeaponType::TwoHandMace,
    WeaponType::Spear,
    WeaponType::Dagger,
    WeaponType::Katana,
    WeaponType::Scythe,
    WeaponType::Staff,
    WeaponType::Wand,
    WeaponType::Tome,
    WeaponType::Bow,
    WeaponType::Crossbow,
    WeaponType::Shield
  };
  return values;
}

inline const char * const *EnumNamesWeaponType() {
  static const char * const names[18] = {
    "None",
    "Sword",
    "TwoHandSword",
    "Axe",
    "TwoHandAxe",
    "Mace",
    "TwoHandMace",
    "Spear",
    "Dagger",
    "Katana",
    "Scythe",
    "Staff",
    "Wand",
    "Tome",
    "Bow",
    "Crossbow",
    "Shield",
    nullptr
  };
  return names;
}

inline const char *EnumNameWeaponType(WeaponType e) {
  if (::flatbuffers::IsOutRange(e, WeaponType::None, WeaponType::Shield)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWeaponType()[index];
}

enum class ArmorType : int32_t {
  None = 0,
  HeavyArmor = 1,
  MediumArmor = 2,
  LightArmor = 3,
  Robe = 4,
  Cloth = 5,
  MIN = None,
  MAX = Cloth
};

inline const ArmorType (&EnumValuesArmorType())[6] {
  static const ArmorType values[] = {
    ArmorType::None,
    ArmorType::HeavyArmor,
    ArmorType::MediumArmor,
    ArmorType::LightArmor,
    ArmorType::Robe,
    ArmorType::Cloth
  };
  return values;
}

inline const char * const *EnumNamesArmorType() {
  static const char * const names[7] = {
    "None",
    "HeavyArmor",
    "MediumArmor",
    "LightArmor",
    "Robe",
    "Cloth",
    nullptr
  };
  return names;
}

inline const char *EnumNameArmorType(ArmorType e) {
  if (::flatbuffers::IsOutRange(e, ArmorType::None, ArmorType::Cloth)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesArmorType()[index];
}

enum class MoveType : int32_t {
  Walk = 0,
  Run = 1,
  Teleport = 2,
  Knockback = 3,
  MIN = Walk,
  MAX = Knockback
};

inline const MoveType (&EnumValuesMoveType())[4] {
  static const MoveType values[] = {
    MoveType::Walk,
    MoveType::Run,
    MoveType::Teleport,
    MoveType::Knockback
  };
  return values;
}

inline const char * const *EnumNamesMoveType() {
  static const char * const names[5] = {
    "Walk",
    "Run",
    "Teleport",
    "Knockback",
    nullptr
  };
  return names;
}

inline const char *EnumNameMoveType(MoveType e) {
  if (::flatbuffers::IsOutRange(e, MoveType::Walk, MoveType::Knockback)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMoveType()[index];
}

enum class MapType : int32_t {
  Town = 0,
  Field = 1,
  Dungeon = 2,
  Raid = 3,
  PvP = 4,
  Instance = 5,
  MIN = Town,
  MAX = Instance
};

inline const MapType (&EnumValuesMapType())[6] {
  static const MapType values[] = {
    MapType::Town,
    MapType::Field,
    MapType::Dungeon,
    MapType::Raid,
    MapType::PvP,
    MapType::Instance
  };
  return values;
}

inline const char * const *EnumNamesMapType() {
  static const char * const names[7] = {
    "Town",
    "Field",
    "Dungeon",
    "Raid",
    "PvP",
    "Instance",
    nullptr
  };
  return names;
}

inline const char *EnumNameMapType(MapType e) {
  if (::flatbuffers::IsOutRange(e, MapType::Town, MapType::Instance)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMapType()[index];
}

enum class MonsterFaction : int32_t {
  None = 0,
  WolfPack = 1,
  GoblinTribe = 2,
  OrcClan = 3,
  UndeadLegion = 4,
  ForestSpirit = 5,
  DragonKind = 6,
  MIN = None,
  MAX = DragonKind
};

inline const MonsterFaction (&EnumValuesMonsterFaction())[7] {
  static const MonsterFaction values[] = {
    MonsterFaction::None,
    MonsterFaction::WolfPack,
    MonsterFaction::GoblinTribe,
    MonsterFaction::OrcClan,
    MonsterFaction::UndeadLegion,
    MonsterFaction::ForestSpirit,
    MonsterFaction::DragonKind
  };
  return values;
}

inline const char * const *EnumNamesMonsterFaction() {
  static const char * const names[8] = {
    "None",
    "WolfPack",
    "GoblinTribe",
    "OrcClan",
    "UndeadLegion",
    "ForestSpirit",
    "DragonKind",
    nullptr
  };
  return names;
}

inline const char *EnumNameMonsterFaction(MonsterFaction e) {
  if (::flatbuffers::IsOutRange(e, MonsterFaction::None, MonsterFaction::DragonKind)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMonsterFaction()[index];
}

enum class JobType : int32_t {
  None = 0,
  Warrior = 101,
  Berserker = 102,
  Knight = 103,
  Paladin = 104,
  DarkKnight = 105,
  Priest = 201,
  Bishop = 202,
  SoulKeeper = 203,
  Necromancer = 204,
  Wizard = 301,
  Pyromancer = 302,
  Cryomancer = 303,
  Stormcaller = 304,
  Geomancer = 305,
  Ranger = 401,
  Hunter = 402,
  Assassin = 403,
  ShadowBlade = 404,
  Druid = 501,
  Summoner = 502,
  Bard = 503,
  Alchemist = 504,
  MIN = None,
  MAX = Alchemist
};

inline const JobType (&EnumValuesJobType())[23] {
  static const JobType values[] = {
    JobType::None,
    JobType::Warrior,
    JobType::Berserker,
    JobType::Knight,
    JobType::Paladin,
    JobType::DarkKnight,
    JobType::Priest,
    JobType::Bishop,
    JobType::SoulKeeper,
    JobType::Necromancer,
    JobType::Wizard,
    JobType::Pyromancer,
    JobType::Cryomancer,
    JobType::Stormcaller,
    JobType::Geomancer,
    JobType::Ranger,
    JobType::Hunter,
    JobType::Assassin,
    JobType::ShadowBlade,
    JobType::Druid,
    JobType::Summoner,
    JobType::Bard,
    JobType::Alchemist
  };
  return values;
}

inline const char *EnumNameJobType(JobType e) {
  switch (e) {
    case JobType::None: return "None";
    case JobType::Warrior: return "Warrior";
    case JobType::Berserker: return "Berserker";
    case JobType::Knight: return "Knight";
    case JobType::Paladin: return "Paladin";
    case JobType::DarkKnight: return "DarkKnight";
    case JobType::Priest: return "Priest";
    case JobType::Bishop: return "Bishop";
    case JobType::SoulKeeper: return "SoulKeeper";
    case JobType::Necromancer: return "Necromancer";
    case JobType::Wizard: return "Wizard";
    case JobType::Pyromancer: return "Pyromancer";
    case JobType::Cryomancer: return "Cryomancer";
    case JobType::Stormcaller: return "Stormcaller";
    case JobType::Geomancer: return "Geomancer";
    case JobType::Ranger: return "Ranger";
    case JobType::Hunter: return "Hunter";
    case JobType::Assassin: return "Assassin";
    case JobType::ShadowBlade: return "ShadowBlade";
    case JobType::Druid: return "Druid";
    case JobType::Summoner: return "Summoner";
    case JobType::Bard: return "Bard";
    case JobType::Alchemist: return "Alchemist";
    default: return "";
  }
}

enum class SkillType : int32_t {
  Active = 0,
  Passive = 1,
  Ultimate = 2,
  Toggle = 3,
  Reaction = 4,
  MIN = Active,
  MAX = Reaction
};

inline const SkillType (&EnumValuesSkillType())[5] {
  static const SkillType values[] = {
    SkillType::Active,
    SkillType::Passive,
    SkillType::Ultimate,
    SkillType::Toggle,
    SkillType::Reaction
  };
  return values;
}

inline const char * const *EnumNamesSkillType() {
  static const char * const names[6] = {
    "Active",
    "Passive",
    "Ultimate",
    "Toggle",
    "Reaction",
    nullptr
  };
  return names;
}

inline const char *EnumNameSkillType(SkillType e) {
  if (::flatbuffers::IsOutRange(e, SkillType::Active, SkillType::Reaction)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSkillType()[index];
}

enum class ZoneAttributeType : int32_t {
  Neutral = 0,
  Holy = 1,
  Dark = 2,
  Fire = 3,
  Ice = 4,
  Lightning = 5,
  Earth = 6,
  Cursed = 7,
  Sacred = 8,
  MIN = Neutral,
  MAX = Sacred
};

inline const ZoneAttributeType (&EnumValuesZoneAttributeType())[9] {
  static const ZoneAttributeType values[] = {
    ZoneAttributeType::Neutral,
    ZoneAttributeType::Holy,
    ZoneAttributeType::Dark,
    ZoneAttributeType::Fire,
    ZoneAttributeType::Ice,
    ZoneAttributeType::Lightning,
    ZoneAttributeType::Earth,
    ZoneAttributeType::Cursed,
    ZoneAttributeType::Sacred
  };
  return values;
}

inline const char * const *EnumNamesZoneAttributeType() {
  static const char * const names[10] = {
    "Neutral",
    "Holy",
    "Dark",
    "Fire",
    "Ice",
    "Lightning",
    "Earth",
    "Cursed",
    "Sacred",
    nullptr
  };
  return names;
}

inline const char *EnumNameZoneAttributeType(ZoneAttributeType e) {
  if (::flatbuffers::IsOutRange(e, ZoneAttributeType::Neutral, ZoneAttributeType::Sacred)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesZoneAttributeType()[index];
}

}  // namespace makga

#endif  // FLATBUFFERS_GENERATED_ENUM_MAKGA_H_
