// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GAMEPACKETID_MAKGA_H_
#define FLATBUFFERS_GENERATED_GAMEPACKETID_MAKGA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace makga {

enum class PacketId : uint16_t {
  None = 0,
  Move = 1001,
  Attack = 1101,
  AttackResult = 1102,
  SkillUse = 1103,
  SkillResult = 1104,
  SkillList = 1105,
  BuffApply = 1106,
  BuffRemove = 1107,
  ActorDeath = 1108,
  ActorResurrect = 1109,
  HpMpSync = 1110,
  InventoryList = 1201,
  ItemPickup = 1202,
  ItemDrop = 1203,
  ItemUse = 1204,
  ItemMove = 1205,
  ItemSplit = 1206,
  ItemLock = 1207,
  EquipItem = 1208,
  UnequipItem = 1209,
  EquipList = 1210,
  ShopOpen = 1301,
  ShopBuy = 1302,
  ShopSell = 1303,
  ShopList = 1304,
  TradeRequest = 1401,
  TradeAccept = 1402,
  TradeDecline = 1403,
  TradeAddItem = 1404,
  TradeRemoveItem = 1405,
  TradeAddGold = 1406,
  TradeReady = 1407,
  TradeConfirm = 1408,
  TradeCancel = 1409,
  TradeResult = 1410,
  AuctionSearch = 1501,
  AuctionList = 1502,
  AuctionRegister = 1503,
  AuctionBid = 1504,
  AuctionBuyNow = 1505,
  AuctionCancel = 1506,
  AuctionMyList = 1507,
  AuctionResult = 1508,
  CraftList = 1601,
  CraftRequest = 1602,
  CraftResult = 1603,
  EnchantRequest = 1701,
  EnchantResult = 1702,
  PartyInvite = 1801,
  PartyInviteResp = 1802,
  PartyLeave = 1803,
  PartyKick = 1804,
  PartyDisband = 1805,
  PartyInfo = 1806,
  PartyMemberSync = 1807,
  PartyLeaderChange = 1808,
  PartyLootChange = 1809,
  GuildCreate = 1901,
  GuildDisband = 1902,
  GuildInvite = 1903,
  GuildInviteResp = 1904,
  GuildLeave = 1905,
  GuildKick = 1906,
  GuildInfo = 1907,
  GuildMemberList = 1908,
  GuildRankChange = 1909,
  GuildNotice = 1910,
  GuildDeposit = 1911,
  GuildWithdraw = 1912,
  DungeonEnter = 2001,
  DungeonEnterResp = 2002,
  DungeonExit = 2003,
  DungeonClear = 2004,
  DungeonInfo = 2005,
  BossPhaseChange = 2006,
  QuestList = 2101,
  QuestAccept = 2102,
  QuestAbandon = 2103,
  QuestComplete = 2104,
  QuestProgress = 2105,
  FriendList = 2201,
  FriendAdd = 2202,
  FriendAddResp = 2203,
  FriendRemove = 2204,
  FriendBlock = 2205,
  FriendUnblock = 2206,
  Whisper = 2207,
  FriendOnline = 2208,
  ChatNormal = 2301,
  ChatZone = 2302,
  ChatWorld = 2303,
  ChatParty = 2304,
  ChatGuild = 2305,
  AchievementList = 2401,
  AchievementUnlock = 2402,
  TitleList = 2403,
  TitleEquip = 2404,
  TitleUnequip = 2405,
  RankingList = 2501,
  SeasonInfo = 2601,
  SeasonReward = 2602,
  SeasonMission = 2603,
  HiddenQuestTrigger = 2701,
  LegendaryForge = 2702,
  FateFragment = 2703,
  SecretDungeonUnlock = 2704,
  MIN = None,
  MAX = SecretDungeonUnlock
};

inline const PacketId (&EnumValuesPacketId())[107] {
  static const PacketId values[] = {
    PacketId::None,
    PacketId::Move,
    PacketId::Attack,
    PacketId::AttackResult,
    PacketId::SkillUse,
    PacketId::SkillResult,
    PacketId::SkillList,
    PacketId::BuffApply,
    PacketId::BuffRemove,
    PacketId::ActorDeath,
    PacketId::ActorResurrect,
    PacketId::HpMpSync,
    PacketId::InventoryList,
    PacketId::ItemPickup,
    PacketId::ItemDrop,
    PacketId::ItemUse,
    PacketId::ItemMove,
    PacketId::ItemSplit,
    PacketId::ItemLock,
    PacketId::EquipItem,
    PacketId::UnequipItem,
    PacketId::EquipList,
    PacketId::ShopOpen,
    PacketId::ShopBuy,
    PacketId::ShopSell,
    PacketId::ShopList,
    PacketId::TradeRequest,
    PacketId::TradeAccept,
    PacketId::TradeDecline,
    PacketId::TradeAddItem,
    PacketId::TradeRemoveItem,
    PacketId::TradeAddGold,
    PacketId::TradeReady,
    PacketId::TradeConfirm,
    PacketId::TradeCancel,
    PacketId::TradeResult,
    PacketId::AuctionSearch,
    PacketId::AuctionList,
    PacketId::AuctionRegister,
    PacketId::AuctionBid,
    PacketId::AuctionBuyNow,
    PacketId::AuctionCancel,
    PacketId::AuctionMyList,
    PacketId::AuctionResult,
    PacketId::CraftList,
    PacketId::CraftRequest,
    PacketId::CraftResult,
    PacketId::EnchantRequest,
    PacketId::EnchantResult,
    PacketId::PartyInvite,
    PacketId::PartyInviteResp,
    PacketId::PartyLeave,
    PacketId::PartyKick,
    PacketId::PartyDisband,
    PacketId::PartyInfo,
    PacketId::PartyMemberSync,
    PacketId::PartyLeaderChange,
    PacketId::PartyLootChange,
    PacketId::GuildCreate,
    PacketId::GuildDisband,
    PacketId::GuildInvite,
    PacketId::GuildInviteResp,
    PacketId::GuildLeave,
    PacketId::GuildKick,
    PacketId::GuildInfo,
    PacketId::GuildMemberList,
    PacketId::GuildRankChange,
    PacketId::GuildNotice,
    PacketId::GuildDeposit,
    PacketId::GuildWithdraw,
    PacketId::DungeonEnter,
    PacketId::DungeonEnterResp,
    PacketId::DungeonExit,
    PacketId::DungeonClear,
    PacketId::DungeonInfo,
    PacketId::BossPhaseChange,
    PacketId::QuestList,
    PacketId::QuestAccept,
    PacketId::QuestAbandon,
    PacketId::QuestComplete,
    PacketId::QuestProgress,
    PacketId::FriendList,
    PacketId::FriendAdd,
    PacketId::FriendAddResp,
    PacketId::FriendRemove,
    PacketId::FriendBlock,
    PacketId::FriendUnblock,
    PacketId::Whisper,
    PacketId::FriendOnline,
    PacketId::ChatNormal,
    PacketId::ChatZone,
    PacketId::ChatWorld,
    PacketId::ChatParty,
    PacketId::ChatGuild,
    PacketId::AchievementList,
    PacketId::AchievementUnlock,
    PacketId::TitleList,
    PacketId::TitleEquip,
    PacketId::TitleUnequip,
    PacketId::RankingList,
    PacketId::SeasonInfo,
    PacketId::SeasonReward,
    PacketId::SeasonMission,
    PacketId::HiddenQuestTrigger,
    PacketId::LegendaryForge,
    PacketId::FateFragment,
    PacketId::SecretDungeonUnlock
  };
  return values;
}

inline const char *EnumNamePacketId(PacketId e) {
  switch (e) {
    case PacketId::None: return "None";
    case PacketId::Move: return "Move";
    case PacketId::Attack: return "Attack";
    case PacketId::AttackResult: return "AttackResult";
    case PacketId::SkillUse: return "SkillUse";
    case PacketId::SkillResult: return "SkillResult";
    case PacketId::SkillList: return "SkillList";
    case PacketId::BuffApply: return "BuffApply";
    case PacketId::BuffRemove: return "BuffRemove";
    case PacketId::ActorDeath: return "ActorDeath";
    case PacketId::ActorResurrect: return "ActorResurrect";
    case PacketId::HpMpSync: return "HpMpSync";
    case PacketId::InventoryList: return "InventoryList";
    case PacketId::ItemPickup: return "ItemPickup";
    case PacketId::ItemDrop: return "ItemDrop";
    case PacketId::ItemUse: return "ItemUse";
    case PacketId::ItemMove: return "ItemMove";
    case PacketId::ItemSplit: return "ItemSplit";
    case PacketId::ItemLock: return "ItemLock";
    case PacketId::EquipItem: return "EquipItem";
    case PacketId::UnequipItem: return "UnequipItem";
    case PacketId::EquipList: return "EquipList";
    case PacketId::ShopOpen: return "ShopOpen";
    case PacketId::ShopBuy: return "ShopBuy";
    case PacketId::ShopSell: return "ShopSell";
    case PacketId::ShopList: return "ShopList";
    case PacketId::TradeRequest: return "TradeRequest";
    case PacketId::TradeAccept: return "TradeAccept";
    case PacketId::TradeDecline: return "TradeDecline";
    case PacketId::TradeAddItem: return "TradeAddItem";
    case PacketId::TradeRemoveItem: return "TradeRemoveItem";
    case PacketId::TradeAddGold: return "TradeAddGold";
    case PacketId::TradeReady: return "TradeReady";
    case PacketId::TradeConfirm: return "TradeConfirm";
    case PacketId::TradeCancel: return "TradeCancel";
    case PacketId::TradeResult: return "TradeResult";
    case PacketId::AuctionSearch: return "AuctionSearch";
    case PacketId::AuctionList: return "AuctionList";
    case PacketId::AuctionRegister: return "AuctionRegister";
    case PacketId::AuctionBid: return "AuctionBid";
    case PacketId::AuctionBuyNow: return "AuctionBuyNow";
    case PacketId::AuctionCancel: return "AuctionCancel";
    case PacketId::AuctionMyList: return "AuctionMyList";
    case PacketId::AuctionResult: return "AuctionResult";
    case PacketId::CraftList: return "CraftList";
    case PacketId::CraftRequest: return "CraftRequest";
    case PacketId::CraftResult: return "CraftResult";
    case PacketId::EnchantRequest: return "EnchantRequest";
    case PacketId::EnchantResult: return "EnchantResult";
    case PacketId::PartyInvite: return "PartyInvite";
    case PacketId::PartyInviteResp: return "PartyInviteResp";
    case PacketId::PartyLeave: return "PartyLeave";
    case PacketId::PartyKick: return "PartyKick";
    case PacketId::PartyDisband: return "PartyDisband";
    case PacketId::PartyInfo: return "PartyInfo";
    case PacketId::PartyMemberSync: return "PartyMemberSync";
    case PacketId::PartyLeaderChange: return "PartyLeaderChange";
    case PacketId::PartyLootChange: return "PartyLootChange";
    case PacketId::GuildCreate: return "GuildCreate";
    case PacketId::GuildDisband: return "GuildDisband";
    case PacketId::GuildInvite: return "GuildInvite";
    case PacketId::GuildInviteResp: return "GuildInviteResp";
    case PacketId::GuildLeave: return "GuildLeave";
    case PacketId::GuildKick: return "GuildKick";
    case PacketId::GuildInfo: return "GuildInfo";
    case PacketId::GuildMemberList: return "GuildMemberList";
    case PacketId::GuildRankChange: return "GuildRankChange";
    case PacketId::GuildNotice: return "GuildNotice";
    case PacketId::GuildDeposit: return "GuildDeposit";
    case PacketId::GuildWithdraw: return "GuildWithdraw";
    case PacketId::DungeonEnter: return "DungeonEnter";
    case PacketId::DungeonEnterResp: return "DungeonEnterResp";
    case PacketId::DungeonExit: return "DungeonExit";
    case PacketId::DungeonClear: return "DungeonClear";
    case PacketId::DungeonInfo: return "DungeonInfo";
    case PacketId::BossPhaseChange: return "BossPhaseChange";
    case PacketId::QuestList: return "QuestList";
    case PacketId::QuestAccept: return "QuestAccept";
    case PacketId::QuestAbandon: return "QuestAbandon";
    case PacketId::QuestComplete: return "QuestComplete";
    case PacketId::QuestProgress: return "QuestProgress";
    case PacketId::FriendList: return "FriendList";
    case PacketId::FriendAdd: return "FriendAdd";
    case PacketId::FriendAddResp: return "FriendAddResp";
    case PacketId::FriendRemove: return "FriendRemove";
    case PacketId::FriendBlock: return "FriendBlock";
    case PacketId::FriendUnblock: return "FriendUnblock";
    case PacketId::Whisper: return "Whisper";
    case PacketId::FriendOnline: return "FriendOnline";
    case PacketId::ChatNormal: return "ChatNormal";
    case PacketId::ChatZone: return "ChatZone";
    case PacketId::ChatWorld: return "ChatWorld";
    case PacketId::ChatParty: return "ChatParty";
    case PacketId::ChatGuild: return "ChatGuild";
    case PacketId::AchievementList: return "AchievementList";
    case PacketId::AchievementUnlock: return "AchievementUnlock";
    case PacketId::TitleList: return "TitleList";
    case PacketId::TitleEquip: return "TitleEquip";
    case PacketId::TitleUnequip: return "TitleUnequip";
    case PacketId::RankingList: return "RankingList";
    case PacketId::SeasonInfo: return "SeasonInfo";
    case PacketId::SeasonReward: return "SeasonReward";
    case PacketId::SeasonMission: return "SeasonMission";
    case PacketId::HiddenQuestTrigger: return "HiddenQuestTrigger";
    case PacketId::LegendaryForge: return "LegendaryForge";
    case PacketId::FateFragment: return "FateFragment";
    case PacketId::SecretDungeonUnlock: return "SecretDungeonUnlock";
    default: return "";
  }
}

}  // namespace makga

#endif  // FLATBUFFERS_GENERATED_GAMEPACKETID_MAKGA_H_
