// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GAMEPACKETID_MAKGA_H_
#define FLATBUFFERS_GENERATED_GAMEPACKETID_MAKGA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace makga {

enum PacketId : uint16_t {
  PacketId_None = 0,
  PacketId_Move = 1001,
  PacketId_MIN = PacketId_None,
  PacketId_MAX = PacketId_Move
};

inline const PacketId (&EnumValuesPacketId())[2] {
  static const PacketId values[] = {
    PacketId_None,
    PacketId_Move
  };
  return values;
}

inline const char *EnumNamePacketId(PacketId e) {
  switch (e) {
    case PacketId_None: return "None";
    case PacketId_Move: return "Move";
    default: return "";
  }
}

}  // namespace makga

#endif  // FLATBUFFERS_GENERATED_GAMEPACKETID_MAKGA_H_
