// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOGINPACKETID_MAKGA_H_
#define FLATBUFFERS_GENERATED_LOGINPACKETID_MAKGA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace makga {

enum LoginPacketId : uint16_t {
  LoginPacketId_None = 0,
  LoginPacketId_Login = 1,
  LoginPacketId_SelectCharacter = 2,
  LoginPacketId_EnterWorld = 3,
  LoginPacketId_MIN = LoginPacketId_None,
  LoginPacketId_MAX = LoginPacketId_EnterWorld
};

inline const LoginPacketId (&EnumValuesLoginPacketId())[4] {
  static const LoginPacketId values[] = {
    LoginPacketId_None,
    LoginPacketId_Login,
    LoginPacketId_SelectCharacter,
    LoginPacketId_EnterWorld
  };
  return values;
}

inline const char * const *EnumNamesLoginPacketId() {
  static const char * const names[5] = {
    "None",
    "Login",
    "SelectCharacter",
    "EnterWorld",
    nullptr
  };
  return names;
}

inline const char *EnumNameLoginPacketId(LoginPacketId e) {
  if (::flatbuffers::IsOutRange(e, LoginPacketId_None, LoginPacketId_EnterWorld)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLoginPacketId()[index];
}

}  // namespace makga

#endif  // FLATBUFFERS_GENERATED_LOGINPACKETID_MAKGA_H_
