// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOGINPACKET_MAKGA_H_
#define FLATBUFFERS_GENERATED_LOGINPACKET_MAKGA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "enum_generated.h"
#include "login_packet_id_generated.h"
#include "result_generated.h"

namespace makga {

struct CharacterInfo;
struct CharacterInfoBuilder;

struct C2S_Login;
struct C2S_LoginBuilder;

struct S2C_Login;
struct S2C_LoginBuilder;

struct C2S_SelectCharacter;
struct C2S_SelectCharacterBuilder;

struct S2C_EnterWorld;
struct S2C_EnterWorldBuilder;

struct CharacterInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CharacterInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHARACTER_UID = 4,
    VT_NAME = 6,
    VT_LEVEL = 8,
    VT_JOB = 10,
    VT_RACE = 12
  };
  uint64_t character_uid() const {
    return GetField<uint64_t>(VT_CHARACTER_UID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t level() const {
    return GetField<int32_t>(VT_LEVEL, 1);
  }
  makga::JobType job() const {
    return static_cast<makga::JobType>(GetField<int32_t>(VT_JOB, 0));
  }
  makga::RaceType race() const {
    return static_cast<makga::RaceType>(GetField<int32_t>(VT_RACE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CHARACTER_UID, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_LEVEL, 4) &&
           VerifyField<int32_t>(verifier, VT_JOB, 4) &&
           VerifyField<int32_t>(verifier, VT_RACE, 4) &&
           verifier.EndTable();
  }
};

struct CharacterInfoBuilder {
  typedef CharacterInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_character_uid(uint64_t character_uid) {
    fbb_.AddElement<uint64_t>(CharacterInfo::VT_CHARACTER_UID, character_uid, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(CharacterInfo::VT_NAME, name);
  }
  void add_level(int32_t level) {
    fbb_.AddElement<int32_t>(CharacterInfo::VT_LEVEL, level, 1);
  }
  void add_job(makga::JobType job) {
    fbb_.AddElement<int32_t>(CharacterInfo::VT_JOB, static_cast<int32_t>(job), 0);
  }
  void add_race(makga::RaceType race) {
    fbb_.AddElement<int32_t>(CharacterInfo::VT_RACE, static_cast<int32_t>(race), 0);
  }
  explicit CharacterInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CharacterInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CharacterInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CharacterInfo> CreateCharacterInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t character_uid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t level = 1,
    makga::JobType job = makga::JobType_Warrior,
    makga::RaceType race = makga::RaceType_Human) {
  CharacterInfoBuilder builder_(_fbb);
  builder_.add_character_uid(character_uid);
  builder_.add_race(race);
  builder_.add_job(job);
  builder_.add_level(level);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CharacterInfo> CreateCharacterInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t character_uid = 0,
    const char *name = nullptr,
    int32_t level = 1,
    makga::JobType job = makga::JobType_Warrior,
    makga::RaceType race = makga::RaceType_Human) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return makga::CreateCharacterInfo(
      _fbb,
      character_uid,
      name__,
      level,
      job,
      race);
}

struct C2S_Login FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_LoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SESSION_TOKEN = 4,
    VT_ACCOUNT_UID = 6
  };
  const ::flatbuffers::String *session_token() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SESSION_TOKEN);
  }
  uint64_t account_uid() const {
    return GetField<uint64_t>(VT_ACCOUNT_UID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SESSION_TOKEN) &&
           verifier.VerifyString(session_token()) &&
           VerifyField<uint64_t>(verifier, VT_ACCOUNT_UID, 8) &&
           verifier.EndTable();
  }
};

struct C2S_LoginBuilder {
  typedef C2S_Login Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_session_token(::flatbuffers::Offset<::flatbuffers::String> session_token) {
    fbb_.AddOffset(C2S_Login::VT_SESSION_TOKEN, session_token);
  }
  void add_account_uid(uint64_t account_uid) {
    fbb_.AddElement<uint64_t>(C2S_Login::VT_ACCOUNT_UID, account_uid, 0);
  }
  explicit C2S_LoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_Login> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_Login>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_Login> CreateC2S_Login(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> session_token = 0,
    uint64_t account_uid = 0) {
  C2S_LoginBuilder builder_(_fbb);
  builder_.add_account_uid(account_uid);
  builder_.add_session_token(session_token);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<C2S_Login> CreateC2S_LoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *session_token = nullptr,
    uint64_t account_uid = 0) {
  auto session_token__ = session_token ? _fbb.CreateString(session_token) : 0;
  return makga::CreateC2S_Login(
      _fbb,
      session_token__,
      account_uid);
}

struct S2C_Login FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_LoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULT = 4,
    VT_CHARACTERS = 6
  };
  makga::Result result() const {
    return static_cast<makga::Result>(GetField<int32_t>(VT_RESULT, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<makga::CharacterInfo>> *characters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<makga::CharacterInfo>> *>(VT_CHARACTERS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_RESULT, 4) &&
           VerifyOffset(verifier, VT_CHARACTERS) &&
           verifier.VerifyVector(characters()) &&
           verifier.VerifyVectorOfTables(characters()) &&
           verifier.EndTable();
  }
};

struct S2C_LoginBuilder {
  typedef S2C_Login Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_result(makga::Result result) {
    fbb_.AddElement<int32_t>(S2C_Login::VT_RESULT, static_cast<int32_t>(result), 0);
  }
  void add_characters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<makga::CharacterInfo>>> characters) {
    fbb_.AddOffset(S2C_Login::VT_CHARACTERS, characters);
  }
  explicit S2C_LoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_Login> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_Login>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_Login> CreateS2C_Login(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    makga::Result result = makga::Result_Success,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<makga::CharacterInfo>>> characters = 0) {
  S2C_LoginBuilder builder_(_fbb);
  builder_.add_characters(characters);
  builder_.add_result(result);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<S2C_Login> CreateS2C_LoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    makga::Result result = makga::Result_Success,
    const std::vector<::flatbuffers::Offset<makga::CharacterInfo>> *characters = nullptr) {
  auto characters__ = characters ? _fbb.CreateVector<::flatbuffers::Offset<makga::CharacterInfo>>(*characters) : 0;
  return makga::CreateS2C_Login(
      _fbb,
      result,
      characters__);
}

struct C2S_SelectCharacter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_SelectCharacterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHARACTER_UID = 4
  };
  uint64_t character_uid() const {
    return GetField<uint64_t>(VT_CHARACTER_UID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CHARACTER_UID, 8) &&
           verifier.EndTable();
  }
};

struct C2S_SelectCharacterBuilder {
  typedef C2S_SelectCharacter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_character_uid(uint64_t character_uid) {
    fbb_.AddElement<uint64_t>(C2S_SelectCharacter::VT_CHARACTER_UID, character_uid, 0);
  }
  explicit C2S_SelectCharacterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_SelectCharacter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_SelectCharacter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_SelectCharacter> CreateC2S_SelectCharacter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t character_uid = 0) {
  C2S_SelectCharacterBuilder builder_(_fbb);
  builder_.add_character_uid(character_uid);
  return builder_.Finish();
}

struct S2C_EnterWorld FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_EnterWorldBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULT = 4,
    VT_ACTOR_ID = 6,
    VT_X = 8,
    VT_Y = 10,
    VT_Z = 12,
    VT_YAW = 14,
    VT_MAP_ID = 16
  };
  makga::Result result() const {
    return static_cast<makga::Result>(GetField<int32_t>(VT_RESULT, 0));
  }
  uint64_t actor_id() const {
    return GetField<uint64_t>(VT_ACTOR_ID, 0);
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  float yaw() const {
    return GetField<float>(VT_YAW, 0.0f);
  }
  const ::flatbuffers::String *map_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAP_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_RESULT, 4) &&
           VerifyField<uint64_t>(verifier, VT_ACTOR_ID, 8) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           VerifyField<float>(verifier, VT_YAW, 4) &&
           VerifyOffset(verifier, VT_MAP_ID) &&
           verifier.VerifyString(map_id()) &&
           verifier.EndTable();
  }
};

struct S2C_EnterWorldBuilder {
  typedef S2C_EnterWorld Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_result(makga::Result result) {
    fbb_.AddElement<int32_t>(S2C_EnterWorld::VT_RESULT, static_cast<int32_t>(result), 0);
  }
  void add_actor_id(uint64_t actor_id) {
    fbb_.AddElement<uint64_t>(S2C_EnterWorld::VT_ACTOR_ID, actor_id, 0);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(S2C_EnterWorld::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(S2C_EnterWorld::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(S2C_EnterWorld::VT_Z, z, 0.0f);
  }
  void add_yaw(float yaw) {
    fbb_.AddElement<float>(S2C_EnterWorld::VT_YAW, yaw, 0.0f);
  }
  void add_map_id(::flatbuffers::Offset<::flatbuffers::String> map_id) {
    fbb_.AddOffset(S2C_EnterWorld::VT_MAP_ID, map_id);
  }
  explicit S2C_EnterWorldBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_EnterWorld> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_EnterWorld>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_EnterWorld> CreateS2C_EnterWorld(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    makga::Result result = makga::Result_Success,
    uint64_t actor_id = 0,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float yaw = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> map_id = 0) {
  S2C_EnterWorldBuilder builder_(_fbb);
  builder_.add_actor_id(actor_id);
  builder_.add_map_id(map_id);
  builder_.add_yaw(yaw);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_result(result);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<S2C_EnterWorld> CreateS2C_EnterWorldDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    makga::Result result = makga::Result_Success,
    uint64_t actor_id = 0,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f,
    float yaw = 0.0f,
    const char *map_id = nullptr) {
  auto map_id__ = map_id ? _fbb.CreateString(map_id) : 0;
  return makga::CreateS2C_EnterWorld(
      _fbb,
      result,
      actor_id,
      x,
      y,
      z,
      yaw,
      map_id__);
}

}  // namespace makga

#endif  // FLATBUFFERS_GENERATED_LOGINPACKET_MAKGA_H_
