// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOGINPACKETID_MAKGA_H_
#define FLATBUFFERS_GENERATED_LOGINPACKETID_MAKGA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace makga {

enum class LoginPacketId : uint16_t {
  None = 0,
  Login = 1,
  SelectCharacter = 2,
  EnterWorld = 3,
  MIN = None,
  MAX = EnterWorld
};

inline const LoginPacketId (&EnumValuesLoginPacketId())[4] {
  static const LoginPacketId values[] = {
    LoginPacketId::None,
    LoginPacketId::Login,
    LoginPacketId::SelectCharacter,
    LoginPacketId::EnterWorld
  };
  return values;
}

inline const char * const *EnumNamesLoginPacketId() {
  static const char * const names[5] = {
    "None",
    "Login",
    "SelectCharacter",
    "EnterWorld",
    nullptr
  };
  return names;
}

inline const char *EnumNameLoginPacketId(LoginPacketId e) {
  if (::flatbuffers::IsOutRange(e, LoginPacketId::None, LoginPacketId::EnterWorld)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLoginPacketId()[index];
}

}  // namespace makga

#endif  // FLATBUFFERS_GENERATED_LOGINPACKETID_MAKGA_H_
