// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PARTYENUM_MAKGA_COMMUNITY_H_
#define FLATBUFFERS_GENERATED_PARTYENUM_MAKGA_COMMUNITY_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace makga {
namespace community {

enum PartyRole : int8_t {
  PartyRole_Leader = 0,
  PartyRole_Member = 1,
  PartyRole_MIN = PartyRole_Leader,
  PartyRole_MAX = PartyRole_Member
};

inline const PartyRole (&EnumValuesPartyRole())[2] {
  static const PartyRole values[] = {
    PartyRole_Leader,
    PartyRole_Member
  };
  return values;
}

inline const char * const *EnumNamesPartyRole() {
  static const char * const names[3] = {
    "Leader",
    "Member",
    nullptr
  };
  return names;
}

inline const char *EnumNamePartyRole(PartyRole e) {
  if (::flatbuffers::IsOutRange(e, PartyRole_Leader, PartyRole_Member)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPartyRole()[index];
}

enum PartyState : int8_t {
  PartyState_Idle = 0,
  PartyState_InDungeon = 1,
  PartyState_InCombat = 2,
  PartyState_MIN = PartyState_Idle,
  PartyState_MAX = PartyState_InCombat
};

inline const PartyState (&EnumValuesPartyState())[3] {
  static const PartyState values[] = {
    PartyState_Idle,
    PartyState_InDungeon,
    PartyState_InCombat
  };
  return values;
}

inline const char * const *EnumNamesPartyState() {
  static const char * const names[4] = {
    "Idle",
    "InDungeon",
    "InCombat",
    nullptr
  };
  return names;
}

inline const char *EnumNamePartyState(PartyState e) {
  if (::flatbuffers::IsOutRange(e, PartyState_Idle, PartyState_InCombat)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPartyState()[index];
}

enum ExpShareType : int8_t {
  ExpShareType_Equal = 0,
  ExpShareType_Contribution = 1,
  ExpShareType_MIN = ExpShareType_Equal,
  ExpShareType_MAX = ExpShareType_Contribution
};

inline const ExpShareType (&EnumValuesExpShareType())[2] {
  static const ExpShareType values[] = {
    ExpShareType_Equal,
    ExpShareType_Contribution
  };
  return values;
}

inline const char * const *EnumNamesExpShareType() {
  static const char * const names[3] = {
    "Equal",
    "Contribution",
    nullptr
  };
  return names;
}

inline const char *EnumNameExpShareType(ExpShareType e) {
  if (::flatbuffers::IsOutRange(e, ExpShareType_Equal, ExpShareType_Contribution)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesExpShareType()[index];
}

enum LootType : int8_t {
  LootType_FreeForAll = 0,
  LootType_RoundRobin = 1,
  LootType_NeedGreed = 2,
  LootType_MIN = LootType_FreeForAll,
  LootType_MAX = LootType_NeedGreed
};

inline const LootType (&EnumValuesLootType())[3] {
  static const LootType values[] = {
    LootType_FreeForAll,
    LootType_RoundRobin,
    LootType_NeedGreed
  };
  return values;
}

inline const char * const *EnumNamesLootType() {
  static const char * const names[4] = {
    "FreeForAll",
    "RoundRobin",
    "NeedGreed",
    nullptr
  };
  return names;
}

inline const char *EnumNameLootType(LootType e) {
  if (::flatbuffers::IsOutRange(e, LootType_FreeForAll, LootType_NeedGreed)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLootType()[index];
}

enum PartyGoalType : int8_t {
  PartyGoalType_Field = 0,
  PartyGoalType_Dungeon = 1,
  PartyGoalType_MIN = PartyGoalType_Field,
  PartyGoalType_MAX = PartyGoalType_Dungeon
};

inline const PartyGoalType (&EnumValuesPartyGoalType())[2] {
  static const PartyGoalType values[] = {
    PartyGoalType_Field,
    PartyGoalType_Dungeon
  };
  return values;
}

inline const char * const *EnumNamesPartyGoalType() {
  static const char * const names[3] = {
    "Field",
    "Dungeon",
    nullptr
  };
  return names;
}

inline const char *EnumNamePartyGoalType(PartyGoalType e) {
  if (::flatbuffers::IsOutRange(e, PartyGoalType_Field, PartyGoalType_Dungeon)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPartyGoalType()[index];
}

}  // namespace community
}  // namespace makga

#endif  // FLATBUFFERS_GENERATED_PARTYENUM_MAKGA_COMMUNITY_H_
