// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VERSION_MAKGA_H_
#define FLATBUFFERS_GENERATED_VERSION_MAKGA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace makga {

enum class Version : int32_t {
  Build = 100,
  MIN = Build,
  MAX = Build
};

inline const Version (&EnumValuesVersion())[1] {
  static const Version values[] = {
    Version::Build
  };
  return values;
}

inline const char * const *EnumNamesVersion() {
  static const char * const names[2] = {
    "Build",
    nullptr
  };
  return names;
}

inline const char *EnumNameVersion(Version e) {
  if (::flatbuffers::IsOutRange(e, Version::Build, Version::Build)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(Version::Build);
  return EnumNamesVersion()[index];
}

}  // namespace makga

#endif  // FLATBUFFERS_GENERATED_VERSION_MAKGA_H_
