// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RESULTTYPE_FB_H_
#define FLATBUFFERS_GENERATED_RESULTTYPE_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace fb {

enum eResult : int32_t {
  eResult_Success = 0,
  eResult_Fail = 1,
  eResult_BufferLackSpace = 2,
  eResult_BufferFailWrite = 3,
  eResult_BufferFailRead = 4,
  eResult_InvalidParameter = 5,
  eResult_NotFoundServer = 6,
  eResult_InvalidIndex = 7,
  eResult_InvenFull = 8,
  eResult_MIN = eResult_Success,
  eResult_MAX = eResult_InvenFull
};

inline const eResult (&EnumValueseResult())[9] {
  static const eResult values[] = {
    eResult_Success,
    eResult_Fail,
    eResult_BufferLackSpace,
    eResult_BufferFailWrite,
    eResult_BufferFailRead,
    eResult_InvalidParameter,
    eResult_NotFoundServer,
    eResult_InvalidIndex,
    eResult_InvenFull
  };
  return values;
}

inline const char * const *EnumNameseResult() {
  static const char * const names[10] = {
    "Success",
    "Fail",
    "BufferLackSpace",
    "BufferFailWrite",
    "BufferFailRead",
    "InvalidParameter",
    "NotFoundServer",
    "InvalidIndex",
    "InvenFull",
    nullptr
  };
  return names;
}

inline const char *EnumNameeResult(eResult e) {
  if (::flatbuffers::IsOutRange(e, eResult_Success, eResult_InvenFull)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNameseResult()[index];
}

}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_RESULTTYPE_FB_H_
