// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SERVERTOWORLDPID_FB_WORLD_H_
#define FLATBUFFERS_GENERATED_SERVERTOWORLDPID_FB_WORLD_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace world {

enum SendPid : uint32_t {
  SendPid_None = 0,
  SendPid_Reg = 1,
  SendPid_Ping = 2,
  SendPid_MIN = SendPid_None,
  SendPid_MAX = SendPid_Ping
};

inline const SendPid (&EnumValuesSendPid())[3] {
  static const SendPid values[] = {
    SendPid_None,
    SendPid_Reg,
    SendPid_Ping
  };
  return values;
}

inline const char * const *EnumNamesSendPid() {
  static const char * const names[4] = {
    "None",
    "Reg",
    "Ping",
    nullptr
  };
  return names;
}

inline const char *EnumNameSendPid(SendPid e) {
  if (::flatbuffers::IsOutRange(e, SendPid_None, SendPid_Ping)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSendPid()[index];
}

/// [ENUM] (C<-GS) Recv Packet id
enum RecvPid : uint32_t {
  RecvPid_None = 0,
  RecvPid_Reg = 1,
  RecvPid_Ping = 2,
  RecvPid_MIN = RecvPid_None,
  RecvPid_MAX = RecvPid_Ping
};

inline const RecvPid (&EnumValuesRecvPid())[3] {
  static const RecvPid values[] = {
    RecvPid_None,
    RecvPid_Reg,
    RecvPid_Ping
  };
  return values;
}

inline const char * const *EnumNamesRecvPid() {
  static const char * const names[4] = {
    "None",
    "Reg",
    "Ping",
    nullptr
  };
  return names;
}

inline const char *EnumNameRecvPid(RecvPid e) {
  if (::flatbuffers::IsOutRange(e, RecvPid_None, RecvPid_Ping)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRecvPid()[index];
}

}  // namespace world
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_SERVERTOWORLDPID_FB_WORLD_H_
