// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SERVERTODBAGENTPID_FB_DBAGENT_H_
#define FLATBUFFERS_GENERATED_SERVERTODBAGENTPID_FB_DBAGENT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace dbagent {

enum SendPid : uint32_t {
  SendPid_None = 0,
  SendPid_Reg = 1,
  SendPid_Ping = 2,
  SendPid_LoginAuth = 3,
  SendPid_LoginSecurity = 4,
  SendPid_GuildCreate = 5,
  SendPid_GuildEnter = 6,
  SendPid_GuildLeave = 7,
  SendPid_NationEnter = 8,
  SendPid_NationLeave = 9,
  SendPid_MIN = SendPid_None,
  SendPid_MAX = SendPid_NationLeave
};

inline const SendPid (&EnumValuesSendPid())[10] {
  static const SendPid values[] = {
    SendPid_None,
    SendPid_Reg,
    SendPid_Ping,
    SendPid_LoginAuth,
    SendPid_LoginSecurity,
    SendPid_GuildCreate,
    SendPid_GuildEnter,
    SendPid_GuildLeave,
    SendPid_NationEnter,
    SendPid_NationLeave
  };
  return values;
}

inline const char * const *EnumNamesSendPid() {
  static const char * const names[11] = {
    "None",
    "Reg",
    "Ping",
    "LoginAuth",
    "LoginSecurity",
    "GuildCreate",
    "GuildEnter",
    "GuildLeave",
    "NationEnter",
    "NationLeave",
    nullptr
  };
  return names;
}

inline const char *EnumNameSendPid(SendPid e) {
  if (::flatbuffers::IsOutRange(e, SendPid_None, SendPid_NationLeave)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSendPid()[index];
}

/// [ENUM] (C<-GS) Recv Packet id
enum RecvPid : uint32_t {
  RecvPid_None = 0,
  RecvPid_Reg = 1,
  RecvPid_Ping = 2,
  RecvPid_LoginAuth = 3,
  RecvPid_LoginSecurity = 4,
  RecvPid_MIN = RecvPid_None,
  RecvPid_MAX = RecvPid_LoginSecurity
};

inline const RecvPid (&EnumValuesRecvPid())[5] {
  static const RecvPid values[] = {
    RecvPid_None,
    RecvPid_Reg,
    RecvPid_Ping,
    RecvPid_LoginAuth,
    RecvPid_LoginSecurity
  };
  return values;
}

inline const char * const *EnumNamesRecvPid() {
  static const char * const names[6] = {
    "None",
    "Reg",
    "Ping",
    "LoginAuth",
    "LoginSecurity",
    nullptr
  };
  return names;
}

inline const char *EnumNameRecvPid(RecvPid e) {
  if (::flatbuffers::IsOutRange(e, RecvPid_None, RecvPid_LoginSecurity)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRecvPid()[index];
}

}  // namespace dbagent
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_SERVERTODBAGENTPID_FB_DBAGENT_H_
